### ISSUE TITLE
Possibility of including this in the API?

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#1001]
I do not know if this will be considered out of the API usage scope but I have this in my `stdafx.h` header file:

```
template<typename T, typename U> static T inline pointer_cast(U src) noexcept
{
    static_assert(sizeof(T) >= sizeof(U), "Invalid pointer cast"); // Check sizes!
    __pragma(warning(suppress:26490)) // Note: no semicolon after this expression!
        return reinterpret_cast<T>(src);
}
```

Ofcourse, you could rename the function if you wanted to but the idea is that in some instances with MFC you have to use `reinterpret_cast` and all the warnings are annoying. This handy overload supresses all the warnings.

I thought it could be added to your library.

**Comment by dmitrykobets-msft** [comment]
Hi @ajtruckle,

This wrapper does not overcome all of the safety flaws of `reinterpret_cast`. This is because, in the general case, if pointer A's size is >= pointer B's size, this does not ensure that pointer B can be used as a pointer A. In fact, in modern environments it is very common for most pointers to have the same size, which would automatically be let through by the `static_assert`. Here is an example from my local machine, using pointers-to-scalar types:

```
std::cout << sizeof(int64_t*) << std::endl; // 8
std::cout << sizeof(float*) << std::endl; // 8
float* d = new float{4.2};
std::cout << *pointer_cast<int64_t*>(d) << std::endl; // 1082549862
```

And comparing the size of the pointed-to object rather than the pointer itself will not help, because `int64_t` is bigger than `float` in the example above:
```
std::cout << sizeof(int64_t) << std::endl; // 8
std::cout << sizeof(float) << std::endl; // 4
```

This is why we discourage using `reinterpret_cast`.

Thanks,
Dmitry

**Comment by dmitrykobets-msft** [comment]
Hi @ajtruckle,

This repo is simply an implementation of the current CppCoreGuidelines standard, which currently does not make any exceptions for `reinterpret_cast`. We have discussed your proposal in the maintainer's sync and you would actually want to re-target this proposal at the CppCoreGuidelines themselves: https://github.com/isocpp/CppCoreGuidelines. 

Thanks,
Dmitry
