### ISSUE TITLE
Handling pointer decay and pointer arithmetic with CUIntArray.

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#1005]
If I can just understand the concepts correctly then I am sure I could apply the principles elsewhere.

Code:
```
void CSyncExclusionsDlg::GetSyncData(CUIntArray aryUIntSyncData[])
{
	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::HomeSpeaker)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::HomeSpeaker)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::AwaySpeaker)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::AwaySpeaker)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::Chairman)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::Chairman)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::Reader)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::Reader)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::Host)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::Host)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::Cohost)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::Cohost)));

	aryUIntSyncData[to_underlying(CPTSDatabase::Sync::WTConductor)].Copy(
		gsl::at(m_aryUIntSynchData, to_underlying(CPTSDatabase::Sync::WTConductor)));
}
```

The first issue is the function parameter. It talks about "no array to pointer decay". It also mentions that it could be wrapped with `gsl::not_null` as we don't test for null. How do I address the pointer decay remark?

The second issue is all these bits:

`aryUIntSyncData[to_underlying(CPTSDatabase::Sync::HomeSpeaker)].Copy(`

It says I should not use pointer arithmetic and use span instead.

What changes should I make here?

**Comment by dmitrykobets-msft** [comment]
Hi @ajtruckle,

The warnings here are due to the fact that the argument `CUIntArray aryUIntSyncData[]` is actually syntactic sugar for `CUIntArray* aryUIntSyncData`, and so any array argument being passed into this function will decay into a raw pointer. This results in loss of bounds information for the array. The warning on this parameter is therefore suggesting that if you truly don't want to use standard-library structures in this code (i.e., `std::vector` / `std::array`), to instead use `gsl::span`, like so:
```
void CSyncExclusionsDlg::GetSyncData(gsl::span<CUIntArray> aryUIntSyncData)
```

The subsequent access operations `aryUIntSyncData[to_underlying(CPTSDatabase::Sync::HomeSpeaker)]` will be bounds-checked, to avoid out-of-bounds access into the array, and so the warnings you see on them about "pointer arithmetic" will disappear as well.

Thanks,
Dmitry

**Comment by ajtruckle** [comment]
Thank you for taking the time to show and explain. I understand this much better now. My project started many years ago and the code we are working with therefore using `CUintArray` etc. Since then I have started to use the other contructs like `std::vector`.
