### ISSUE TITLE
Build with latest GSL fails in Visual Studio Community 2022 due to defines and namespaces

### ISSUE THREAD

**Issue by peterdell** [microsoft/GSL#1034]
Using the latest version of GSL results in errors because VS truncates the names of defines:
Workaround defines are too long for MS Visual Studio Community 2022

#define GSL_MSVC_USE_STL_NOEXCEPTION_WORKAROUND

must be shorted to GSL_MSVC_USE_STL_NOEXCEPTION_WO
Likewise 

#if defined(GSL_USE_STATIC_CONSTEXPR_WORKAROUND)

must be shortened. I've used #if defined(GSL_USE_STATIC_CONSTEXPR_WO).

Still then the build warns about with
1>lib\gsl/util(28): warning RC4067: unexpected characters following '#if/#elif' directive; newline expected
1>
1>lib\gsl/util(28): warning RC4067: unexpected characters following '#if/#elif' directive; newline expected
1>
#if defined(__has_include) && __has_include(<version>)

and then fails with

1>lib\gsl/assert(92): error RC2104: undefined keyword or key name: namespace

**Comment by dmitrykobets-msft** [comment]
Hi @peterdell is the truncation warning by any chance RC4011? If not, what is it? Because most references I can find online to this warning are for VS2010/2012. And the fact that you still get the other warnings/errors even after shortening the macro is suspicious, since that would indicate that the truncation isn't the root of the problem. I'll try and repro this locally as well when I get the chance.

**Comment by peterdell** [comment]
Yes, it's RC4011 and they are "just" warnings. Fixing them does not fix the build error regarding the namespace. I've reverted to C++ 17 and the 3.x version of GSL, still it fails with the same "namespace" error in the assert parts.

1>------ Build started: Project: profiles, Configuration: Debug Win32 ------
2>------ Build started: Project: dis6502, Configuration: Debug Win32 ------
2>lib\gsl/gsl_assert(91): warning RC4011: identifier truncated to 'GSL_MSVC_USE_STL_NOEXCEPTION_WO'
2>
2>lib\gsl/gsl_assert(113): warning RC4011: identifier truncated to 'GSL_MSVC_USE_STL_NOEXCEPTION_WO'
2>
2>lib\gsl/gsl_assert(129): warning RC4011: identifier truncated to 'GSL_MSVC_USE_STL_NOEXCEPTION_WO'
2>
2>lib\gsl/span(347): warning RC4011: identifier truncated to 'GSL_USE_STATIC_CONSTEXPR_WORKAR'
2>
2>lib\gsl/span(408): warning RC4011: identifier truncated to 'GSL_USE_STATIC_CONSTEXPR_WORKAR'
2>
2>lib\gsl/span(753): warning RC4011: identifier truncated to 'GSL_USE_STATIC_CONSTEXPR_WORKAR'
2>
2>lib\gsl/gsl_assert(89): error RC2104: undefined keyword or key name: namespace

**Comment by peterdell** [comment]
Hello Dmitry,
thanks for taking the time. I've pushed my version here:
https://sourceforge.net/p/dis6502/git/ci/master/tree/

**Comment by dmitrykobets-msft** [comment]
@peterdell,
I tried building f06f23, and 4e4a3d but I was getting build errors unrelated to this issue and I didn't try and resolve them. Are you able to make a minimal repro instead? If not, I'm not sure if I'll be able to make progress on this, since then it would seem like this is an issue with your project and not GSL (especially since C++ 17 and the 3.x version of GSL also fail for you).

**Comment by peterdell** [comment]
Yes, it must have something to do with the include order and some conditional assembly.
For now, I've resorted to removing <gsl/span> again from my default headers and implementing my own minimal version for my use case without dependencies to other GSL headers. Now it compiles. So thanks for your help so far.
