### ISSUE TITLE
gsl.h and log4cpp headers conflict

### ISSUE THREAD

**Issue by Jeff-Mott-OR** [Microsoft/GSL#142]
A very simple reproducer is described at http://stackoverflow.com/questions/33061432/is-the-new-gsl-incompatible-with-log4cpp

**Comment by gdr-at-ms** [comment]
This might be because `array_view` is pulling in `<limits>`, which on Windows unfortunately pulls in macros `min` and `max` defined by Windows headers.  
It is arguably a bug in the VS headers since C++ specifically says those aren't macros.
Maybe GSL could '#undef' those macros after including `<limits>`; but arguably that would be papering over a bug in the VS headers.

**Comment by neilmacintosh** [comment]
I'm ok with putting in push/pop for the macro versions of min/max under a #define that identifies MSVC. Sure, it would be "papering over " bug in the VS headers, but it would also let the GSL operate more easily in that environment. Jeff, would you be interested in offering a fix?

**Comment by neilmacintosh** [comment]
After thinking some more, I remembered that if you simply define NOMINMAX for your compilation, then the offending macros in windef.h (the ultimate source) will go away.
