### ISSUE TITLE
Building with C++11 using gcc or clang

### ISSUE THREAD

**Issue by MatthiasKauer** [Microsoft/GSL#175]
Hi,
I'm wondering if forcing C++14 for GCC and Clang is a design decision.
Could / should the readme mention that somehow?

I'm having trouble building with std=c++11 on gcc 5.2 and it appears that the tests would always use std=c++14 on this compiler, judging from the cmake config [here](https://github.com/Microsoft/GSL/blob/ffdf97b83d79b3ef969f6d44e0899ffcc7932017/tests/CMakeLists.txt)
Related discussion also: https://github.com/Microsoft/GSL/issues/131

I'm worried about this because if I start developing towards the C++14 standard with clang/gcc on Linux, I foresee major issues compiling on Windows later on. On the other hand, if the library builds with VS 2013, it should also (more or less) build with -std=c++11 under gcc, or am I mistaken here?
I assume this has to do with macros that avoid new constexpr functionality.
Without going into detail, is there a chance to make this run with C++11 or is it simply out of scope for you? Or is this an issue on my side and you'd actually expect this to work?

Kind regards,
Matthias Kauer

**Comment by neilmacintosh** [comment]
@MatthiasKauer We want to use C++14 for the GSL, as it lets us have a simpler implementation of the abstractions in the library. The library aims to support good, modern C++ programming style - as recommended by the C+ Core Guidelines. Understandably we want to use all the latest language goodness in pursuit of that goal. So yes: creating a version that explicitly targets C++11 is out-of-scope for us.

The library builds with VS2013 and 2015 because that reflects a specific practical need within Microsoft. It does so by using ugly by useful conditional-compilation workarounds. As MSVC improves its standards conformance you will see less of these workarounds in place for the newest version of MSVC. 

How to structure your own code to be portable across compilers is a separate issue. However, I would suggest taking a look at MSVC 2015 Update 1 RC and the conformance improvements that compiler has (even compared to MSVC 2015, which was itself a big leap forward). We are making big strides towards better conformance with each release, and that remains a key focus for the team. It may be that - dependending on the exact language features you use from C++14 - porting to MSVC is not so bad for you.

I will update the readme file to try and capture some of this thinking.

**Comment by MatthiasKauer** [comment]
Thanks for clarifying this. I hope I haven't come across as aggressive. After watching your cppcon talks, I'm maybe a little too eager to use this project.
