### ISSUE TITLE
size instead of length?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/GSL#181]
std::vector and most other containers do have size() but do not have length()
Shouldn't span use size() too?

std::string does have both but I'd just drop length and use size everywhere.

BTW, what's the proper place to discuss stuff? This issue tracker?

**Comment by neilmacintosh** [comment]
@OlafvdSpek, rather than "instead of" we have opted for "in addition to". The current design has `span` with both `size()` and `length()`. It is probably not immediately obvious in the current implementation because `size()` is declared on the `basic_span` implementation type (that will be removed soon-ish).
