### ISSUE TITLE
max misinterpreted in MFC project

### ISSUE THREAD

**Issue by daixtrose** [Microsoft/GSL#253]
Hi!
I am not sure if you want to fix this, but MFC has some odd definition for max. Therefore 

```c++
static const SizeType max_value = std::numeric_limits<SizeType>::max();
```
fails with an error message simmilar to this one:

packages\microsoft.gsl.0.1.1.0\build\native\include\span.h(90): warning C4003: not enough actual parameters for macro 'max'

This is easily fixed with a dirty trick, namely extra parentheses
```c++
static const SizeType max_value = (std::numeric_limits<SizeType>::max)();
```
Your decision if you want to support the usage of GSL in such an old environment ...

KInd Regards,

Markus

**Comment by gdr-at-ms** [comment]
This is an issue with Windows headers.  The best fix is for you to #undef that macro after including Windows headers.  Because it is likely to cause problems elsewhere.

**Comment by neilmacintosh** [comment]
@gdr-at-ms  has it right here @daixtrose. The issue is not with GSL source but with Windows headers. A popular solution is to `#define NOMINMAX` before including any headers that include `windows.h`. That way `windows.h` will not `#define` macros for min and max. [This relevant thread ](http://stackoverflow.com/questions/4913922/possible-problems-with-nominmax-on-visual-c)on StackOverflow may be useful.
