### ISSUE TITLE
span::operator[] does not flag access with negative index

### ISSUE THREAD

**Issue by kyku** [Microsoft/GSL#293]
This following code prints random data on the console. Tested under Linux with GCC 6.1 and CLANG 3.8.0.
```
#include <iostream>
#include "gsl/span.h"

int main()
{
  int array[3] = {1,2,3};
  gsl::span<int> span(array);
  std::cout << span[-1] << '\n';
}
```

**Comment by neilmacintosh** [comment]
@kyku the code you have in that sample is not legal according to the specification for `span`. Specifically, the argument supplied to `operator[]` must be `>=0` and `< size()`. This requirement is tested in the library implementation using an `Expects` statement, which indicates a precondition.

This implementation of the GSL allows you to configure how contracts are enforced, so depending on your configuration choice, you may see either a call to `std::terminate()`, an exception thrown, or nothing at all. So whether the illegal access is flagged is ultimately your choice (and I strongly encourage that you use the `std::terminate` option so that it is flagged).

**Comment by kyku** [comment]
@neilmacintosh My point was that you std::terminate() when the index >= size(), but fail to do so when index < 0. What is the point of detecting out-of-bound errors on one side of the range and leaving them undetected on the other side?
