### ISSUE TITLE
Issues with GSL on a project requiring it: "does not match expected signature 'gsl::span .."

### ISSUE THREAD

**Issue by ProfessorKaos64** [Microsoft/GSL#300]
Why is this error being thrown by GSL? The upstream maintainer of this project cannot determine the cause due to the Windows-focused skillset he has. 

```
build/rpcs3-0.0.0.6+20160322git+bsos/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature 'gsl::span<const wchar_t, -1l>& gsl::span<const wchar_t, -1l>::operator=(const gsl::span<const wchar_t, -1l>&)'
CMake Error at cmake_modules/cotire.cmake:1703 (message):
  cotire: error 1 precompiling
  /build/rpcs3-0.0.0.6+20160322git+bsos/obj-x86_64-linux-gnu/rpcs3/cotire/rpcs3_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake_modules/cotire.cmake:3233 (cotire_precompile_prefix_header)


rpcs3/CMakeFiles/rpcs3.dir/build.make:57: recipe for target 'rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch' failed
make[3]: *** [rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch] Error 1
```

* [project issue](https://github.com/RPCS3/rpcs3/issues/1610)
* [Backported pacakges](http://packages.libregeek.org/SteamOS-Tools/pool/main/l/llvm-toolchain-3.6/)
* [Debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/rpcs3/debian)

**Comment by neilmacintosh** [comment]
Hello @ProfessorKaos64. I took a look at the project issue you referenced and it looks as though this has been fixed for you with a Clang update. Note, however that the GSL also received an update recently that may help this issue go away (by placing some operators in the correct namespace, rather than having them mistakenly in the global namespace).
