### ISSUE TITLE
size of span, signed versus unsigned

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#322]
I guess this is more of an request for information rather than a bug.

Why is the index_type of a span a std::ptrdiff_t which is a signed type rather than something like a size_t which is generally unsigned. In general standard library containers and string use size_t.

The only use of it as a negative value I can see is the Extent template parameter defaulting to -1 to indicate dynamic but that could have been numeric_limits<size_t>::max( ) or some magic sentinel.

Anyway it does cause one issue for me which is that constructing a span from a type like a vector causes a compiler warning. This is caused by the constructor
constexpr span(Container& cont) : span(cont.data(), cont.size())
which assigns a unsigned to a signed integer.  My suggestion would be to add
#pragma warning(disable : 4365) // signed/unsigned mismatch
to the _MSC_VER stuff at the top of the header.

**Comment by davidhunter22** [comment]
Note I did re-read your awesome p0122r3 on this where you state "Using a signed index type helps avoid
common mistakes that come from implicit signed to unsigned integer conversions when users employ
integer literals" However I wonder if using a signed value for span while carrying on using unsigned everywhere else in the standard library will actually cause more confusion as it would seem to be a special case. I think if you can make this case for span you can make it for the entire standard library. Maybe span is a special case, other than it still being designed, which I don't understand.

**Comment by gdr-at-ms** [comment]
If the rest of the Standard Library can be realistically changed to use the signed integer type, that would be great.  But, I don't think that ought to happen for the span choice to be effective. I am less worried about "special case" than span failing to help us catch these subtle bugs.

**Comment by neilmacintosh** [comment]
@davidhunter22 the standard library does use unsigned types for size measurements, but for containers (the only data structures that the library currently contains). `span` is one of the first new view types to be proposed for the standard library. As such, we would like it to take a different approach and blaze the trail for a new approach.

For "v2" of the standard library the nature of the size type will be up for discussion across all types. However, until then, there is still benefit from having this view type used a signed size type.

Regardless, I'll definitely add the MSVC suppression to `<span>`.

**Comment by davidhunter22** [comment]
Ok makes sense to me. An alternative to the suppression would be to add another constructor that differs to the current one only in taking a size_t but I suspect that might cause other issues.

**Comment by ewil** [comment]
I've encountered the same frustrations due to the ptrdiff_t/size_t conversion. What should projects that want to use both the standard library and GSL do to integrate the two while avoiding the conversion issue and maintaining readable code?

**Comment by neilmacintosh** [comment]
@ewil, is the code unreadable merely because you are inserting casts? If you are initializing a `gsl::span` from say, a `std::vector`, then does the from-Container constructor not do the work for you? (admittedly, I haven't got around to suppressing the warnings yet).

**Comment by ewil** [comment]
Yeah I had been inserting casts. I felt the result was less readable than the original code. I heard about GSL in a CppCon talk and wanted to try integrating it into packet parsing code where I had been working extensively with both std::string and char*,size_t arguments. I was too concerned to about the implications of casting away or disabling the warnings myself - partly because I'm unsure of what they fully are - so ended up backing out the integration.

More documentation or rationale about ptrdiff_t versus size_t would help. Until I encountered GSL, read the issues here, and did subsequent reading in various places, I had no idea size_t was undesirable. I still don't really understand the issue to be honest, but I'd like to. It seems like if negative values aren't used as indices to a container but allowing for them introduces a theoretical range mismatch with standard library containers, makes integration with preexisting code that uses size_t more difficult, adds negative values to validate against, what is the advantage ptrdiff_t offers to balance that out?

**Comment by gdr-at-ms** [comment]
Understand the request for more documentation -- although this is a very old topic that has been rehashed over the last two decades.

There is one note though: this difference doesn't make use of GSL and standard containers more difficult or less readable -- you just have to write the code appropriately, most of the time  you end up with something elegant. Talking from experience here.  

If you have containers in your program where the difference between `end()` and `begin()` exceeds the precision of `ptrdiff_t` then have much bigger problem (more likely) or you are already doing something so specialized that `span<T>` wouldn't help you anyway if it had used `size_t` (unlikely).

**Comment by rianquinn** [comment]
@gdr-at-ms do you use "-Wsign-conversion" and "-Wconversion"? This was at least where we ran into the issues as casting was needed all over the place when dealing with the GSL and the STL.

**Comment by gdr-at-ms** [comment]
@rianquinn : I do.  I suppose the question is what sort of code patterns do you write for this to be a real problem.

**Comment by rianquinn** [comment]
@gdr-at-ms to be honest I cannot remember the specifics as it was about a month ago when we integrated the GSL into the hypervisor, but I do remember (as I reported this same [issue](https://github.com/Microsoft/GSL/issues/339)), being annoyed that I had to use static_cast on numeric_limit<> to compare the result with the span. 

That being said, I actually agree with the larger argument. Now that we have 64bits, we can spare one of them for error handling. Its just annoying that the STL and GSL don't agree, and you end up with static_casts to fix the issue. I really hope that in future versions of the STL, there are plans to address this (i.e. size_t -> int64_t). If the STL never gets changed, it would seem to me the GSL should follow suit since it's a breading ground for STL code.

**Comment by gdr-at-ms** [comment]
yeah, actually the "bigger problem" is more pronounced with 32-bit.  It is no accident that `ssize_t` was introduced by some operating system interfaces.  The `size_t` thing was well known to be a real problem and a mistake long ago.  We can't just preach "consistency" (however defined) so we can repeat the very same mistakes we want to correct. Sorry.

**Comment by ewil** [comment]
Just for reference this is one example of what I ended up with from roughly a month ago:

```
// Original
void ConfigFile::setBinary(const std::string &key, const void *data, size_t size) { ... }

void ConfigFile::setString(const std::string &key, const std::string &value) {
	setBinary(key, value.data(), value.size());
}
```

```
// With GSL
void ConfigFile::setBinary(const std::string &key, const gsl::span<const char> &data) { ... }

void ConfigFile::setString(const std::string &key, const std::string &value) {
	if (value.size() > static_cast<size_t>(std::numeric_limits<gsl::span<const char>::index_type>::max())) {
		throw std::runtime_error("String too long");
	}

	setBinary(key, {value.data(), static_cast<const gsl::span<const char>::index_type>(value.size())});
}
```

GSL seems awesome and I'd like to use it, but the potential for bugs when mixing ptrdiff_t and size_t scares me. Would it be reasonable for the GSL to include a function for compatibility with std::size_t-based code, even if all it does is check range and perform the cast? Maybe an stdsize() function that converts to std::size_t? That way it's not making a guarantee to convert to unsigned size, but rather whatever type std::size_t happens to be in the standard library, then if/when that type changes it won't be an issue?

As it is, I could foresee users disabling conversion warnings project-wide or ignoring warnings during compilation because there are too many. Then in situations where it matters, a crucial overflow could be missed that leads to exploitability -- for example, an overflow in a server application that ends up leaking a large amount of data to clients. And yes the solution there is to write correct code in the first place but the larger question is how easy does the language and library selection make it to do that? That's the gap I was hoping GSL can fill since it's easier, clearer, and less error prone to pass around a span than pointer/size pairs, which could be and frequently are erroneously mismatched as far as bugs go.

**Comment by MikeGitb** [comment]
My take on this: The constructor of `gsl::span` should check for overflow of the size parameter when constructed from a container. Then you wouldn't even need the separate `setString()` function.

**Comment by neilmacintosh** [comment]
@ewil the guidance is that when constructing a span and explicitly providing an unsigned size value, then you should either use `gsl::narrow_cast()` (if you feel confident the value will always be in range) or `gsl::narrow()` (if you would like a runtime check to ensure it is in range).

The from-container constructor has now been updated (thanks to PR #382) to automatically use `gsl::narrow()` to follow this guideline.

I think that for now, that addresses this specific issue, but if you have other specific cases where you think an additional utility function would help, please feel free to raise another issue.

**Comment by FSMaxB** [comment]
I would like to have a constructor for span that takes a `size_t` and then uses `gsl::narrow` internally.

My code is littered with conversions all over the place, it's really horrible.

Also note that on 32 bit systems, this will prevent creating spans bigger than 2GiB, which is certainly possible otherwise, especially on PAE systems with more than 4GiB of RAM.

I also propose a new size member function, something like `usize()` that returns a `size_t`. This would prevent me from doing conversions every time I call code that doesn't use GSL (or C Code for example).
