### ISSUE TITLE
Feature Request: Finally.ignore()

### ISSUE THREAD

**Issue by rianquinn** [microsoft/GSL#335]
C++ exceptions are amazing, but they introduce an issue with how to handle state. The commit / rollback pattern is amazing at handling this:

http://stackoverflow.com/questions/10983791/c-transaction-like-pattern-for-all-or-nothing-work

Basically, it allows you to do the following:

```
auto cor1 = CommitOrRollback([]{
    undo action1
});

action1();

auto cor2 = CommitOrRollback([]{
    undo action2
});

action2();

cor1.commit();
cor2.commit();
```

gsl::finally is exactly the same thing, but is missing the "commit" function. Since the "finally" operation is sort of backwards, I propose calling it "ignore" and can be implemented doing the following (tested and already working in our repo).

```
void ignore() noexcept { invoke_ = false; }
```

This added API would not affect how it is currently used, but would add the ability to prevent the action from executing based on a condition, which means it would be able to be used for rolling back state in the event of an exception, something that IMO should be integral to the C++ stack.

**Comment by neilmacintosh** [comment]
@rianquinn to make sure this issue gets broad attention and the discussion it deserves, you might want to open a copy of it over at http://github.com/isocpp/CppCoreGuidelines.

**Comment by viboes** [comment]
@rianquinn I don't think finally should support transactions.

You should be able to implement a transaction like you want on top of finally.
You need to define a transaction object that needs to be committed when success.
Then you can use finally with a lambda that has the transaction object on its closure. The lambda needs to check for the state of the transaction. You need `std::uncaught_exceptions()` (Note the s) to count the level of unwinding. All this should of course be wrapped on specific classes/functions so that the use is friendly.

`std::uncaught_exception()` without 's' is not usable in this context.

**Comment by rianquinn** [comment]
Please see the C++ Core Guidelines thread.

**Comment by hsutter** [comment]
Maintainers' call: As of now the Guidelines have not added an `ignore` or `dismiss`. If they add it in the future with a description of what to call it and how it works, then this implementation should implement it and we can reopen this issue.
