### ISSUE TITLE
Where can I find the documentation of the library?

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#34]

**Comment by neilmacintosh** [comment]
The best place to look for documentation around usage of the library is currently the Core Guidelines over at https://github.com/isocpp/CppCoreGuidelines.

**Comment by viboes** [comment]
I believed the GSL was ready to use. Without  documentation How to know if something is part of the library? 

I would label the issue as a task.

**Comment by viboes** [comment]
Sorry, but what is a deferred closed issue. Cannot we reopen an issue?

**Comment by neilmacintosh** [comment]
Yes, it can always be reopened.

I'm not sure how it got the "deferred"..I would blame it on my fingers being inaccurate when choosing a label from the list.

It's closed because the specification for the library will live over with the Core Guidelines (and is currently under development). This is tracked by https://github.com/isocpp/CppCoreGuidelines/issues/144.
