### ISSUE TITLE
Semantic of comparison operators

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#345]
Is there really a requirement for gsl::span to have overloads for relational operators like `==` and `<` and even then, should they be defined in terms of the elements of the ranges they refer to instead of the ranges themselves (just compare the pointers and sizes)?

A common advice (I don't know, if it is actually best practice) is to only overload operators, if their semantic is obvious and use named functions otherwise. At least I found the current semantics pretty surprising, as it behaves like a simple pointer/size pair in all other situations: in particular, `operator=`  doesn't copy elements and span also doesn't own the elements it points to (other than e.g. containers).

The other side is that I can think of very few scenarios, where I'd actually need those operators. So the additional burden of typing something like `compare(span1,span2)` would be rather small, but of course just, because my experience and imagination are limited doesn't mean there are not common use cases (I'd love to hear about them). 

Mind you, I'm are not talking about `string_view` or `string_span`. There the semantics are imho much less controversial and I can think of many more usecases.

**Comment by viboes** [comment]
@MikeGitb I agree that span is not a value type and so it shouldn't base its comparison operators on its contents. Note that span assignment doesn't copy the values, only the pointer and size.

While I'm for the default equality operators (comparing pointer and size), the order comparison operators have no sens if we have default equality. It is like ordering intervals.

**Comment by neilmacintosh** [comment]
There are two aspects that led to the current design:

1. Consistency with `string_span` (which, while superseded by `string_view` in the standard library, shares the same behavior in this regard). It seems very odd that one view is "ok" to have value-based comparison operators but the other is not. If people *want* to compare elements rather than pointers when they compare two views of characters (and they do), then it seems suspicious to argue that other element types are different somehow.

2. `span` is an abstraction: a view over some contiguous data. The underlying pointer is implementation detail. It seems sensible to define the operators for the abstraction in terms of the abstraction, not in terms of its implementation detail. Besides, there is already a way to do comparisons of underlying pointers, simply call .data() and then compare the pointers. 

I'd note that WG21's Library Evolution Working Group took a straw poll and there was strong support for the current definition of the comparison operators.

With all that said, I can imagine `span` without any comparison operators, just named comparison functions, I suspect it would be clunkier to use, but perhaps that is the new world that views should live in. I have no particularly strong personal opinion on that front.

However, I would very strongly object to making `span` support any comparison operators that only consider the underlying pointer and size. I think that will lead to confusion.

**Comment by neilmacintosh** [comment]
@viboes I don't follow how `std::string_view` is a value type. It is a view type. In fact, it is really, conceptually, the same as `gsl::span`: a view over a container. So I don't think you can just dismiss the fact that `std::string_view` already provides comparison operators that behave in exactly the same way as those of `gsl::span`.

`gsl::span` is not designed solely as a replacement for pointer+size. To think so is to misunderstand the purpose of a view type. `gsl::span` exists to decouple interfaces from the details of storage where it is not relevant to them. So rather than passing a `const std::vector<T>&' just so you can search for an element, pass a `gsl::span<T>' instead. That allows callers to use a `std::vector`, or `std::array`, or even a `T*` plus length if necessary as the underlying storage without affecting the caller. The fact that `gsl::span` happens to use a `T*` as its implementation method for abstracting over those different containers is just an implementation detail. It is one we happen to expose to support ease of interop with legacy code that is heavily pointer-based. Just because we want to interoperate does not mean we want to also follow the semantics of the legacy approach.

I'm not sure how I would distingush between "shallow" and "deep" views in any way other than your desired comparison behavior. So is it really a meaningful distinction?

I understand why complex numbers and intervals don't do comparisons other than equality. A `span` is a very different concept, so argument by analogy there is not helpful.

**Comment by viboes** [comment]
IMHO comparison when provided must be coherent with the assignment semantic. If the assignment doesn't make copies of the value types, the comparison shouldn't use the value type. `std::vector`, `std::string` assignment copies its element and so it makes sens to define comparison using the contained elements. 

Imagine you have two spans based on the same array pointing to different parts of the array that contain the same values. These two spans are views of different parts of the same array. Do you believe that it is natural to consider both spans equals? 

Note that `std::string_view` is a non-mutable view and so the external behavior doesn't depend on where the view is pointing to. `span` on the other side are mutable and as such, there is observable behavior that depends on where the span is pointing to. I  believe this makes a major difference.

Note also that the standard uses `std::equal` to compare for deep equality of /ranges/.
Would the Range TS require the Ranges to be EqualityComparable?

**Comment by MikeGitb** [comment]
@neilmacintosh: That a `gsl::span` uses a pointer and a size internally might be an implementation detail. That it **refers** to a contiguous range of elements (rather than containing those elements) is not. To my understanding it is its very purpose. 
Now I don't claim that reference (vs element wise) comparison this is the more logical, more widespread or more useful semantic. Just that there are many reasons why one might expect that semantic and hence should not be overlooked. And as I said, I tend to err on the side of caution when implementing operator overloads whose semantics are not obvious. Especially, if I rarely use them to begin with. 

Of course `string_view` and span are very similar, but there are imho some important differences:
-  `string_view` only allows read access to the underlying string, hence the identity of the underlying string is less important. 
- It always refers to a string which most of the time is treated as a single value (not a sequence of chars variables) and in many cases, one can actually see a `string_view` object as just another representation of the same string value (especially when referring to a string literal).
- Comparisons of strings via the `<` and `==` - operators are very common operations. So if `string_view` is to be a practical replacement for e.g. `const std::string&` parameters, it should have those operators implemented and they should be implemented with the same semantics as for `std::string`. For a general `span<T>` which replaces a `vector<T>&` I see (again from my limited experience) much less need for those operators.

`string_span` is something in between and I don't know what I'd expect here - in particular because I don't know yet what the typical use cases are supposed to be. 

Now just to wrap this up: Personally I don't care too much either way as I'll will probably use them very rarely either way. I mainly raised that issue because I consider this a somewhat controversial design decision that merited some discussion/explanation and wanted to see what others thought about it.

**Comment by viboes** [comment]
From Alex Stepanov "Fundamentals of Generic Programming"

"Once we have identified the parts of an object which must be tested for equality, we know from the earlier discussion that at least those parts must be copied by copy constructors or assignment operators. In particular, these operators must make copies of remote parts, rather than simply copying the pointers to them."

**Comment by neilmacintosh** [comment]
@MikeGitb I don't mind you bringing up the discussion, it is a completely reasonable question. In considering the analogy with `string_view` you make some assumptions I find interesting.

First: that the identity of underlying string is less important just because the elements are read-only. I'm afraid that without more explanation of why you think that is so, I find it a non sequitur. @viboes makes a similar claim, but again doesn't make a link that I can see between element mutability and comparison semantics that seems logical. I am not meaning to frustrate either of you here. I am sure there is a reason you both feel that element mutability is significant in changing comparison semantics, but I need it stated differently (somehow) to understand that reasoning.

By way of explaining my lack of understanding, does that mean that you'd be fine with the existing semantics when it is `span<const T>` but want the semantics to change when it is `span<T>`? You both write as if `span` elements are always mutable, which is not guaranteed in any way. It depends entirely on the mutability of the element type provided.

@MikeGitb your next two points somehow seem to want to make an arbitrary distinction between `std::string` and `std::vector`. You consider the relationship between a container of characters (`std::string`) and a view over that container (`string_view`) different from that between a container of `T` (`std::vector`) and its view (`std::span`). I can hear that you want this to be so, but I don't understand this position. How is a sequence of characters (a string) so fundamentally different from a sequence of (say) lexical tokens?

I think the argument that I have heard so far that I do understand is that there should be a link between assignment and comparison, made by @viboes. I'd need to consider that more carefully, but it is certainly the clearest to me. I'd note that `string_view` breaks that rule, as assignment of `string_view` objects does not assign the underlying sequences. @viboes would you want `string_view` changed to meet those criteria too? If not, does it just come back to element mutability again?

`string_view` is going to be heavily used (at least, that is the intent of its inclusion in the library). `span` shares precisely the same semantics around assignment and comparison. To me, that consistency seems pretty reasonable.

**Comment by galik** [comment]
I'm going to agree with @neilmacintosh and give my thoghts on why I feel the current semantics are correct for how I envisage using `gsl::span`. I have been investigating `std::experimental::string_view` for some time and I am sure I will use it heavily.

IMO the whole point of *view* objects is to give the semantic *impression* that you are dealing with the actual *viewed* data. I want *encapsulation* to *trick* me into thinking that a `gsl::span` is a first class container that I can substitute for (say) a `std::vector` or a `std::array` for the majority of my operations.

I want to be able to put my *view* objects into containers and have them exhibit the same *ordering* characteristics you would expect from any contiguous container when sorted. I want to be able to `std::find` sub-sequences the same way with my *view* objects as with any *container* object. Behavior different from that would be *unexpected* and *undesirable* to me.

The *technicalities* of whether two *views* actually point to the very same memory locations are not something i want to have to deal with if I can avoid it. Not for *normal data processing*. I can see I might need that information when checking *invariants* (aka bug-hunting). But I don't want the things I do to check the *validity* of my data to negatively impact on the logic of how I go about processing that actual data. 

The only fly in this ointment I see is the *assignment* semantics being that underlying data is not copied. Even this seems reasonable to me because the *view* of the final result is closer to what one would expect from a container. By that I mean:

```cpp
gsl::span<int> sp1 = v1; // v1 == {1, 2, 3, 4}
gsl::span<int> sp2 = v2; // v2 == {5, 6, 7, 8, 9, 10}

sp1 = sp2; // now sp1 == sp2 which we also get from v1 = v2

```

If the underlying data was *copied* then the above would only hold true when `sp1.size() <= sp2.size()`. That would not look *semantically similar* to `v1 = v2`.

So, to me, even *assignment* seems more natural and expected when the underlying data is *not* copied. This reinforces the subterfuge that *views* are designed to perpetrate; conning me into thinking I am actually using a container.

**Comment by galik** [comment]
I was just thinking that, semantically, *view* objects are a little bit like *references* that can be re-bound by assignment. They behave as an *alias* in most operations but assignment causes them to be re-bound (or re-aliased). Another way to look at them is like *auto-dereferencing* pointers that automatically dereference in all things *except* re-assignment.

**Comment by MikeGitb** [comment]
@galik: One of us is mixing up semantics with syntactics. According to my definition of those two terms, they might **syntactically** be similar to c++-references (you don't have to de-reference them with `*` or `->`), but semantically they are imo much more like pointers (can be reassigned, can be null and assignment doesn't copy the referenced values).

@neilmacintosh: I'll try to explain my point of view more detailed, please let me know if I forgot to answer an aspect of your question.
Please keep in mind this is mostly about why I perceive `string_view` different from `span<T>`. Most of it is not necessarily an argument for an `operator==` which compares identities instead of values.

> First: that the identity of underlying string is less important just because the elements are read-only. I'm afraid that without more explanation of why you think that is so, I find it a non sequitur. 

That is certainly the weakest argument and in my mind I actually mixed up immutable data (e.g. a const variable) with an immutable reference to data that might actually be mutable (as `string_view`, const reference). Still, if I e.g. have a parameter that is read-only, I usually don't care much  whether it is a copy or a reference to the original object or if I two const references reference the same object or not. However, if I modify a parameter those distinctions becomes very important.

> By way of explaining my lack of understanding, does that mean that you'd be fine with the existing semantics when it is `span<const T>` but want the semantics to change when it is `span<T>`? You both write as if span elements are always mutable, which is not guaranteed in any way. It depends entirely on the mutability of the element type provided.

I'm aware that T can also be const resulting in `span<T>` providing a constant view of the range, but I certainly would not recommend to change the semantics of overloaded operators (or imho any function) based on whether T is const or not. So from the library perspective I tend to see constness of T as a property of T, whereas `string_view` always serves as a constant reference, so it is more of a property of string_view itself. But again: const vs. non-const is certainly the less important aspect of it.

> your next two points somehow seem to want to make an arbitrary distinction between `std::string` and `std::vector`. You consider the relationship between a container of characters (`std::string`) and a view over that container (`string_view`) different from that between a container of `T` (`std::vector`) and its view (`std::span`). I can hear that you want this to be so, but I don't understand this position. How is a sequence of characters (a string) so fundamentally different from a sequence of (say) lexical tokens?

My point is that most of the time I don't see a string as a simple sequence of chars - just as I don't treat a number as a sequence of digits. To me, a string like e.g. "Hello" is one possible value of a string variable (be it `std::string` or some other type) rather than an array of size 6, containing the characters 'H','e','l','l','o','\0'. Just as the number 12 is one possible value of an integer variable, not just the sequence of the digits 1 and 2. Hence I also don't see a `std::string` as a container of characters and if I have to store/process a sequence of otherwise unrelated individual characters, I'd rather use `std::vector<char>` instead of `std::string` because for me, they do represent different concepts (not in the c++ concepts-TS sense).

This is mirrored by the fact that the operations I use most frequently on strings are things like comparison operators that use strings as a whole (or at least substrings), whereas with vector it is much more often about the individual elements. Just think about it: How often do you use a `std::vector<T>` as a key in a map? How often do you sort a `std::vector<std::vector<T>>` lexicographical? How often do you sort the individual characters in a string? How often are you processing individual characters without looking at the predecessor or successor? There are of course examples for all that (e.g. make a string all capital letters), but at least in my code the tendency is clear.

**Comment by viboes** [comment]
@neilmacintosh Yes mutability is important. 

```
span<T> a = f();
span<T> b = a;
assert(a==b);
update(a); // make the contents different without changing the view memory
```
Now, even if we have change a , a==b.

`string_view` doesn't allow to change the contents in the same way span does and so doesn't has this problem. 

From the same Stepanov paper

" Our next axiom says that we intend the C++ copy semantics:

(3) T a = c; T b = c; a = d; assert(b==c);

Here, after assigning the same value c to both a and b, we expect to be able to
modify a without changing the value of b. In fact, we want an even stronger
condition. If zap is an operation which always changes the value of its operand, we
expect the following to hold:

(4) T a = c; T b = c; zap(a); assert(b==c && a!=b);

That is, b and c do not continue to be equal simply because their values were
changed along with a’s, but rather because changing a’s value did not change theirs.
"

**Comment by MikeGitb** [comment]
So I guess everything has been said and for better or for worse, I think it is too late to make subtle semantical changes anyway.

@neilmacintosh: Just to understand the policy here, are OPs supposed to close such issues themselves once the discussion it has run it's course or are you keeping them open on purpose?
