### ISSUE TITLE
Add find function for string_span

### ISSUE THREAD

**Issue by sezaru** [microsoft/GSL#364]
Maybe I'm missing something, but how does one find a string position in a string_span object?

The only way I found was using std::find, but that returns a iterator, which doesn't work when using it with the .subspan, .first, .last methods from string_span which requires a int.

**Comment by galik** [comment]
I recently had to write my own `find_first_not_of` and `find_last_not_of` external functions in order to implement a `trim` function on a `string_span`. I suspect it may be a good idea to write a basic string manipulation library for `string_span`. I would imagine splitting a `string_span` into a `multi_span` would be so much faster than current string splitting routines that return a vector of strings. But maybe they are better as free functions? Perhaps then they could be crafted to apply to more types (like `vector<byte>`).

**Comment by neilmacintosh** [comment]
@galik has the right idea here. The design direction for `string_span` was to be as simple and safe as possible, and have common manipulation functions as free functions.

**Comment by Xazax-hun** [comment]
While I agree that it is good to have free functions in general, but let's also look at the state of the art in other libraries.
* `std::basic_string_view` has `starts_with`, `ends_with`, `find`, `rfind`, `find_first_of`,  etc.
* `llvm::StringRef` has all the same or very similar methods as `std::basic_string_view`

While most (if not all) of these functions can be free functions having them as member functions matching the STL interface have several advantages including:
* Easier migration path from `const std::string&` to using `string_span`
* Easier migration path from `string_span` to `std::basic_string_view`
* Better general familiarity with the interface for the most of the developers

I do not know if having an easy migration path to and from the `gsl` library is a goal. If no, I think the last bullet point might still be something that would be worth to consider.

What are the contra arguments of having those methods other than they could be free functions?

**Comment by galik** [comment]
Well this is where I was coming from.

BTW, I think, when it comes to the `STL`, it is a bit of a grey area whether or not `std::string` is considered to be included. The whole design of the `STL` gets its power from separating the *containers* from the *algorithms*. The only concessions from that are when a generic *algorithm* is less efficient than a built in one (such as `find` on ordered types).

I assume the `std::string` class has member functions because it is more of a specific purpose kind of container. Plus that kind of interface meets more traditional expectations. For those reasons it doesn't really conform to `STL` philosophy in that respect (though it does in others). It also sacrifices some of the re-usability that the `STL` philosophy promotes.

Personally I think the "traditional", built in, string interface makes string parsing harder. At least for me it does. But I didn't realize it was harder until I had gotten more familiar with `STL` philosophy. Now I find dealing with indexes to be awkward and messy and I prefer to work with ranges of characters and functions that return iterators or regions within those ranges. 

I understand your point about interoperability of the types. But writing these as free functions has the added benefit (because of `STL` philosophy) that the function can equally be applied to **all** those types. They don't have to be written once for a `std::string`, *once again* for a `std::string_view` and *yet again* for `gsl::string_span`.

Now I get that those functions are *already written* for `std::string` and `std::string_view`. But the question is when are we going to stop rewriting the same functions over and over again every time we make a new type?

By choosing to use *free functions* we are adhering to `STL` philosophy (which `std::string`'s internal functions don't) and we get to only write them once for all future types we may create. Also, any **new** functions we write will automatically apply to all the different types be it `std::string`, `std::string_view` or `gsl::string_span` or `my_weird_string_type`.

Imagine working on string splitting, string trimming and string joining functions. If these were implemented in `std::string` then everyone who produced a *string like type* would have to write their own versions of those functions to be compatible with `std::string`. But by making them external and generic they only need to be written once and automatically they work with all the different *string like* types.

They would even work with `std::vector<char>` (or even `std::vector<something_else>`) if needed...

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
