### ISSUE TITLE
question: why no span.at()? Why no unique_ptr -> span?

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#402]
I'm working on some paging code, and I have to hold two lists, one is to the physical pages / directories being used by memory, and the other is to a list of my own PTE objects. The list in physical hardware has to be exactly 4K in size, so I cannot use `std::vector`, but at the same time my list of PTE objects can be. So to prevent the use of two `gsl::span` classes I use `std::vector` for my PTE objects, and I use `std::unique_ptr`/ `gsl::span` for the physical pages / directories (since the `[]` that `std::unique_ptr` provides is useless now that we have the Core Guidelines)

So a couple of questions:
- I have to use `.get()` to create the span. It would be nice to just pass a `std::unique_ptr` directly to span. It's a small thing but I feel like it's slowly eating away at my sole each time I see it. 
- Why is there no `.at()` for span? It's actually weird to me that there is a `[]` since we seem to be deprecating it's use in the STL but no `.at()` which is what we have to use in the STL. When looking at my code, half of it uses `.at()` and the other half uses `[]` (depending on whether your using the vector, or the span). The inconsistency is confusing.

**Comment by neilmacintosh** [comment]
Hi @rianquinn! You make an interesting point about `unique_ptr`. I guess it currently "falls through the cracks" because it doesn't meet the standard library's criteria for contiguous container. I think that's definitely worth considering adding - support for simplified `unique_ptr` and `shared_ptr` construction.

Can we spin off a separate issue to track that feature request?

Regarding `at()`: there's already a free-function version of `at()` in the GSL. It should work for any container that is currently not range-checked on `[]` (array, `std::array`, `std::vector`) and I think it should be specialized for `span`. Would that be useful to you?

**Comment by rianquinn** [comment]
I can toss in a PR for the `unique_ptr` and `shared_ptr` so that we can discuss it there. Adding the constructors for those should be pretty simple I think. 

As for `at()`, providing an overload for span in at is fine, but it seems to me that there should just be an `at()` in span itself. To be honest.... I'm confused as to why there is a `[]` operator at all for span. Take for example `std::vector`. The major difference between `at` and `[]` is `at` provides bounds checks as stated [here](http://en.cppreference.com/w/cpp/container/vector/at). Seems to me, for consistency, span should at the very minimum have the same function, but the purest side of me questions why span has `[]` at all since the `std::vector` version doesn't use bounds checks, and thus span is acting differently (i.e. span's `[]` is bounds checked and `std::vector`'s is not, and thus just looking at the code, you cannot tell unless you happen to know which type your looking at). 

The nice thing about `at` is even in the STL, all of the random access containers have `at` and they are all bounds checked, so there is consistency. I can look at the code and know right away that I'm dealing with a safe operation.

**Comment by neilmacintosh** [comment]
@rianquinn a PR would be great, thanks!

The thinking behind the GSL is that any accesses to sequences of elements should be bounds-checked and `span` embodies that philosophy. Where the bounds checks are unnecessary, good compilers can eliminate them. So providing the most syntactically natural form for accessing elements with a bounds-check (`[]`) on `span` makes sense.

We don't like the idea that the syntax of `[]` should mean "not bounds checked", just because that happens to be the unfortunate decision that was made with `std::vector`.

You are right, the `at()` in GSL builds on the consistent meaning from the standard library of "bounds checked".

**Comment by rianquinn** [comment]
Yeah, that makes a lot of sense to me. Adding `at()` to span IMO would simply give people an option so that if your mixing span's and vectors in the same code, you are using the same function (i.e. `xxx.at(i)` instead of having `[]` in some cases and `at` in others, and not really knowing if your looking at safe code, or unsafe code that you need to convert. If your always using span, then `[]` seems fine, but I still think span should at least still provide an `at` so that people have the option for consistency.

**Comment by MikeGitb** [comment]
A question for the long run: Is there anything in the standard, that actually forbids bounds checking on `std::vector::operator[]`? Assuming the core guidelines get sufficient traction in the community and compilers become "good enough" in optimizing those checks, I'd actually like to see `[  ]` becoming bounds checked by default (at least for std::vector, std::array, string, etc -not necessarily for iterators) and a separate function being introduced which guarantees zero overhead.

**Comment by gdr-at-ms** [comment]
@MikeGitb : No, there is none.  In fact, only very few people use 'at()', and that isn't for lack of education for the last two decades.  It just isn't the natural notation for C and C++ programmers.  The natural notation is `[]` and that is the one you want to bound check because that is the most common form and that is where you will find the likely bugs coming from out-of-bound access.

**Comment by neilmacintosh** [comment]
Thanks for the PR @rianquinn. Much as I dislike the `at()/[]` dichotomy in the standard library, I recognize that `at()` exists on `std::vector` and friends, and people might find it a useful way of spelling `[]` in generic code, so I think it`s a useful addition to GSL `span`.

**Comment by neilmacintosh** [comment]
Now that we've had the PR and split the two issues I think we can close this issue. Thanks everyone.
