### ISSUE TITLE
Is `not_null` for use with pointers to arrays or not?

### ISSUE THREAD

**Issue by hpesoj** [Microsoft/GSL#417]
Sections [I.12](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i12-declare-a-pointer-that-must-not-be-null-as-not_null) and [F.25](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f25-use-a-zstring-or-a-not_nullzstring-to-designate-a-c-style-string) of the C++ Core Guidelines suggest that `not_null` is designed to be used with C-style strings (indeed, the `length` function used as an example would presumably need to increment the pointer somehow), but the [current implementation](https://github.com/Microsoft/GSL/blob/master/gsl/gsl) suggests `not_null` is to be used only with pointers that reference a stand-alone object and explicitly `delete`s a number of pointer arithmetic operations. This is an apparent contradiction that needs resolving.

**Comment by neilmacintosh** [comment]
Thanks for the comment @hpesoj. There is no contradiction here. `not_null` can be used to pass around pointers to null-terminated strings, which we acknowledge will unavoidably exist for some time to come.

However, this does not mean we want to encourage using those pointers to access the elements of the string directly (i.e. via pointer arithmetic) as to do so is error-prone. Instead, there are safer C++ constructs for doing so, like the `string_view` on its way in C++17.

So I would assume that a function like `length()` in the example, is probably going to use a standard library facility (like `std::char_traits`) to measure the length of the string, rather than iterating over each element looking for the null-terminator.

**Comment by hpesoj** [comment]
Thanks for the reply @neilmacintosh. Would you be able to clarify exactly what the design goals and rationale for `not_null` are? At the moment it isn't so clear to me.

My reading of the C++ Core Guidelines leads me to believe that a `not_null<T*>` is merely a `T*` that should not be null. This is also the interpretation I assume most people would arrive at if they saw `not_null<T*>` for the first time. Nowhere in the guidelines can I find anything that suggests `not_null` further narrows the interface of `T*`. I assumed that every other pointer-like operation would be supported by `not_null`, including pointer arithmetic.

If `not_null` supports indirection semantics, array semantics, and ownership semantics then why shouldn't it also support iterator semantics?

```c++
*p = 42; // indirection semantics
p[2] = 21; // array semantics
delete p; // ownership semantics
p++; // iterator semantics
```

Why limit this particular use of pointers? Is there a reason why `T*` when used as an iterator doesn't need the protection `not_null` provides? And if it is important for `not_null` to provide extra restrictions beyond ensuring that it is not null, shouldn't there exist a counterpart to enforce said restrictions for pointers that _can_ be null? Something like the `maybe_null` type that was removed?

_p.s. I was wrong to want to use pointer arithmetic operations with a `zstring`; pointer arithmetic should be used only with pointers that represent iterators, not those that represent arrays/strings (array to pointer decay makes it easy to confuse the two). The main operation I would expect to be able to use with `not_null<zstring>` is the subscript operator, which has not been deleted (though you did entertain the idea [here](https://github.com/Microsoft/GSL/issues/399))._

**Comment by neilmacintosh** [comment]
@hpesoj Thanks for the thoughtful questions! I think your description of `not_null` is very accurate: it is conceptually just a `T*` that should not be null, with a tiny bit of code to ensure that invariant holds. So it is a pretty simple thing.

Not using pointers to access arrays of data is clearly addressed by the Core Guidelines in multiple places. Look at the guidelines [Bounds.1: Don't use pointer arithmetic](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#bounds1-dont-use-pointer-arithmetic-use-span-instead) and [I.13: Do not pass an array as a single pointer](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i13-do-not-pass-an-array-as-a-single-pointer) as examples. 

So a key principle of programming within the guidelines is that a raw pointer only refers to a single object. If you want to pass and refer to more than one object, then pass a container (`std::vector`, `std::string`, `std::array`, `std::map`...) or view (`std::string_view`, `gsl::span`) of some kind. 

In the case that you're dealing with an API that really must accept a sequence passed using a `not_null`, then it must contain some other information as well to designate the length of the sequence: either a terminator, a length, or maybe another pointer. In that case, the suggested usage pattern is to immediately construct a view or container from those input parameters. That way you can take advantage of a better interface for accessing sequences, rather than relying on pointer arithmetic.

So this is all a long-winded way of saying that `not_null` assumes it operates within the model I've described, and so has no need of the arithmetic operations that would allow it to be used for array access.

In that spirit, yes, I think we really should remove the subscript operator as well (I had forgotten it was there to be honest). 

Ownership is slightly different again. Let's set aside the corner case of `not_null<owner<T>>` for a moment, as it is really designed just for legacy code and rare low-level cases. In general, you don't want `not_null` used to pass around ownership at all. You want an owning type like `unique_ptr`.

**Comment by hpesoj** [comment]
> Ownership is slightly different again. Let's set aside the corner case of not_null<owner<T>> for a moment, as it is really designed just for legacy code and rare low-level cases. In general, you don't want not_null used to pass around ownership at all. You want an owning type like unique_ptr.

@neilmacintosh If `not_null<owner<T>>` is designed for legacy and low-level code, isn't is also conceivable that `not_null<T>` could in general be used for legacy and low-level code? I had assumed this this was a prime use case for `not_null`. Disabling subscript and arithmetic operations would be a major barrier to use in legacy and low-level code.

**Comment by neilmacintosh** [comment]
@hpesoj Absolutely! But I think you may not be following my point, which is about the difference between using something on the declaration of a function (the interface) as opposed to its body (implementation). If you have `not_null<T>` because you need to take a pointer to an array and (for some reason) cannot change callers to pass you a `span<T>`...then that does not argue in favor of allowing pointer arithmetic on `not_null<T>`. It argues in favor of using `span<T>` inside the body of the function to access that array, rather than doing subscript and arithmetic on the `not_null<T>`. And using `span<T>` to do operations on sequences should certainly not be a barrier to legacy and low-level code.

**Comment by hpesoj** [comment]
@neilmacintosh Okay, so let's say I have a function that takes a pair of pointers as iterators:

```c++
void foo(int* begin, int* end) {
    for (int* it = begin; it != end; ++it) { … }
}
```

I want to increase the safety of my API, and I don't want to modify the way the API is called because that would break a thousand and one other things in my expansive legacy codebase. What the C++ Core Guidelines recommend is that I change the API to use `not_null`, and change my implementation to use `span`:

```c++
void foo(not_null<int*> begin, not_null<int*> end) {
    for (int i : span<int>(begin, end)) { … }
}
```

If this is the case, then that helps me understand what you are aiming for: `not_null<T>` is designed to hold _any_ pointer, no matter what it represents (reference, array, iterator, owning or non-owning), but it explicitly removes all array-like and iterator-like operations because it wants to encourage the use of `span`. Would you say this is correct?

**Comment by neilmacintosh** [comment]
@hpesoj Yes. That is correct, with one exception regarding "owning" cases. What you have written is exactly right for the non-owning case.

If you are passing around ownership, then the Guidelines recommend you pass an owning pointer-type. Ideally that is either `std::unique_ptr`, `std::shared_ptr`, `std::vector` or another container type that encapsulates ownership behavior. In the least-preferred case, where legacy requirements constrain you, you could pass a `gsl::owner<T>`.

`not_null` currently does not play well with those owning types, and I'm not sure it makes sense to try and do so.
