### ISSUE TITLE
Question: Is it possible to avoid misuse of gsl::byte?

### ISSUE THREAD

**Issue by jonitis** [Microsoft/GSL#456]
Hello,

I was playing with gsl::byte and VS2015 and was surprised that actually current implementation does not protect against improper use of gsl::byte.

```
    // gsl::byte b0 { 0x55 };   // wanted form, but c++17 only
    auto b1 = gsl::to_byte<0x155>();  // ok - static_assert at compilation time, but verbose
    auto b2 = gsl::byte(0x155);       // BAD: does not prevent truncation
```
The problem with 3rd line is that it is old C-style cast of too large integer value to enum. With default warning level /W3 I do not even get warning about value truncation. Only /W4 produces warning C4310 = "cast truncates constant value".

I understand that enum class was chosen because of efficiency and ABI compatibility, but it lacks constructor and thus can't validate argument validity. Using static_cast, gsl::narrow_cast or {} initialization form would also work. But if one uses C style cast (hoping that it is constructor call) then problem can be hidden. That much for modern c++ expressiveness of library type over built-in keyword :)

Can you at least enforce truncation error to be an error?

`#pragma warning(error : 4310)
`

P.S.
I am aware about reasoning to add to_byte()
https://github.com/Microsoft/GSL/issues/329

**Comment by neilmacintosh** [comment]
Thanks for the question @jonitis! 

So this is really a question of implementation, rather than design. As long as C-style casts exist, then people can misuse them. If someone ran that code either under a checker for the Core Guidelines, then it would flag the C-style cast and tell them not to do that :-). As you've noted, our compiler (and others) will also flag the potential truncation with the relevant warning level enabled. I wouldn't want to add the `#pragma` to GSL, as it is poor form to change people's warning/error level and treatment just through inclusion of a header.

It might be an idea that - once `byte` is standardized - to make the truncation warning fire at lower warning levels when the compiler seens it occurring for a `byte`.

**Comment by jonitis** [comment]
Hello,

Thanks for clarification. Closing the ticket, but if you have minute to answer slightly unrelated question. What is the recommended way to convert between containers of gsl::bytes and other octet types, e.g. vector<gsl::byte> and vector<uint8_t>?
