### ISSUE TITLE
Add move_owner() and reset_owner() functions to simplify correct use of owner<T>

### ISSUE THREAD

**Issue by neilmacintosh** [microsoft/GSL#476]
As per the Lifetimes paper.

**Comment by tiagomacarios** [comment]
@neilmacintosh can u share the paper?

**Comment by martinmoene** [comment]
[Lifetime Safety: Preventing Leaks and Dangling (PDF)](https://github.com/isocpp/CppCoreGuidelines/raw/master/docs/Lifetimes%20I%20and%20II%20-%20v0.9.1.pdf)
Version 0.9.1.2
Herb Sutter and Neil MacIntosh, 2015-12-02

**Comment by Daniel599** [comment]
@neilmacintosh Did you mean `move_owner` and `release_owner`? I can't find reset_owner in the paper.
```c++
template<class T>
void move_owner(owner<T>& dst, owner<T>&& src)
 { delete dst; dst=src; src=nullptr; }
template<class T>
auto release_owner(owner<T>&& src) -> owner<T>
 { owner<T> tmp=src; src=nullptr; return tmp; }
```

**Comment by PeeyushRawat** [comment]
i want to work on this.

**Comment by hsutter** [comment]
Maintainers' call: The design for `owner<T>` has atrophied and no longer exists in the Lifetime profile and has only one leftover mention in the Guidelines that ends with "???" so it's not well specified. We'll open an issue in the Guidelines for this: isocpp/CppCoreGuidelines#1710. Because the GSL design and feature set is owned by the C++ Core Guidelines, we'll wait to see if they choose to specify this fully so we can implement it, and in the meantime we'll close this feature request. If it does get specified please reactivate this issue when there's a conclusion.
