### ISSUE TITLE
final_act destructor exception specification

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#484]
The function called in the final_act destructor shouldn't throw.
Do we want to limit to functions that don't throw?
If yes, should it be constrained at compile time?

If not, what happens when the function throws?
Do we want the exception scape the destructor or do we want to terminate there?

**Comment by neilmacintosh** [comment]
@viboes Note that `final_act::~final_act` is marked `noexcept`. So that answers the question of what will happen if the supplied function throws: according to the language standard, `std::terminate()` will be called ;-)

I don't think we want to limit `final_act` to only accept functions that do not throw. The current design allows the user to decide whether they want to take the risk of `std::terminate()` being called, and indicates that risk in the standard, language-defined way.
