### ISSUE TITLE
initializer_list span constructor

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#499]
Thoughts on adding an initializer_list span constructor?

```cpp
constexpr span(std::initializer_list<std::remove_const_t<element_type>> list) : storage_(list.begin(), list.size()) {}
```

I recently had to create a class that had an initializer_list constructor and had to copy the contents of the list which requires a span to do safely, but had to manually construct the span. The above constructor removes that so that you can do something like:

```cpp
buffer(std::initializer_list<data_type> list)
{
    auto &&data_span = get_span();
    auto &&list_span = gsl::span<const data_type>(list);

    gsl::copy(list_span, data_span);
}
```

Obviously we can also add the make_span version of this to further simplify this code.

**Comment by CaseyCarter** [comment]
A `span` constructor that accepts rvalue initializer lists is an enormous footgun, since e.g. `auto s = span<int const>{1,2,3};` references an array whose lifetime ends at the `;`.

A `span` constructor that accepts lvalue initializer lists, however, is safer and satisfies your use case. Notably range-v3's generic contiguous range `span` constructor [already accepts lvalue `initializer_list`s](https://wandbox.org/permlink/MbHF3jnAU58dxHOp).

**Comment by MikeGitb** [comment]
Related: #459 and #137

**Comment by CaseyCarter** [comment]
I should also point out that the obvious workaround for when you "know" that the use is safe, say because you know the reference won't/can't outlive the temporary, is to write an rvalue-to-lvalue converter:
```c++
template<class T>
constexpr T& footgun(T&& t) noexcept { return t; }
```
which you can use to explicitly acknowledge that you are entering dangerous territory and you accept the consequences:
```c++

```

**Comment by rianquinn** [comment]
Yeah, it would not be smart to use span with a temporary like that, but span has that issue with a lot of things (i.e. its not limited to initializer lists in this case). As for the current implementation, I tried using the existing constructors which the same issue which is why I had to add the above code to my current set of patches to the GSL. Seems it should be supported since initializer lists are a C++ feature that encapsulate a basic array which is unsafe to use on it's own.

**Comment by neilmacintosh** [comment]
I think the best way to resolve this issue is to update the "from-container" constructors to be a little more forgiving (e.g. use `std::data`) as @CaseyCarter suggests and has also been requested at WG21 meetings.

I think that's a more generic path that should make lvalue `initializer_list`s work correctly while not needing to explicitly endorse `initializer_list` in some way.

**Comment by CaseyCarter** [comment]
> I think the best way to resolve this issue is to update the "from-container" constructors to be a little more forgiving (e.g. use std::data) as @CaseyCarter suggests and has also been requested at WG21 meetings.

[range-v3 span](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/span.hpp#L146) has exactly two converting constructor signatures:
```c++
template<typename Rng>
using CompatibleRange =
    meta::and_<meta::bool_<!Same<span, uncvref_t<Rng>>()>,
        SizedRange<Rng>, ContiguousRange<Rng>,
        std::is_convertible<concepts::ContiguousRange::element_t<Rng>(*)[], T(*)[]>>;
template<typename Rng>
using DynamicConversion = meta::bool_<
    N == dynamic_extent || (range_cardinality<Rng>::value < cardinality{})>;

template<typename Rng,
    CONCEPT_REQUIRES_(CompatibleRange<Rng>()),
    CONCEPT_REQUIRES_(DynamicConversion<Rng>())>
constexpr span(Rng &&rng)
    noexcept(noexcept(ranges::data(rng), ranges::size(rng)))
    : span{ranges::data(rng), detail::narrow_cast<index_type>(ranges::size(rng))}
{}

template<typename Rng>
using StaticConversion = meta::bool_<
    N != dynamic_extent && range_cardinality<Rng>::value == N>;

template<typename Rng,
    CONCEPT_REQUIRES_(CompatibleRange<Rng>()),
    CONCEPT_REQUIRES_(StaticConversion<Rng>())>
constexpr span(Rng &&rng)
    noexcept(noexcept(ranges::data(rng)))
    : span{ranges::data(rng), N}
{}
```
Both are constrained via "concepts" to accept contiguous ranges with compatible element types. The first is only viable when either the `span` has dynamic extent or the source range has dynamic extent (in range-v3 speak `range_cardinality<Rng>::value < cardinality{}` means that `Rng` has dynamic extent). The second is only viable when the source range has the same static extent as the `span`. These two signatures handle everything contiguous: builtin arrays, different `span` specializations, `vector`, `string`, lvalue `initializer_list`, `std::array`, `iterator_range<T*>`, even future contiguous ranges.

I'm certain this is where we want `span` to be, we just don't quite have the tools to specify it yet. I plan to propose the `Contiguous` concepts from range-v3 for the Ranges working paper in JAX. I suspect by the time `span` and ranges are ready to merge into the IS we'll be able to specify these constructors simply and properly with a dash of concepts and a couple sentences of text.

**Comment by neilmacintosh** [comment]
I'm going to close out this issue as `span` has now made its way into the Working Draft of C++20 standard. That version has no explicit support for an lvalue `initializer_list`, but it does specify the from-container constructor to accept containers that have `std::data` and `std::size` defined for them...so an lvalue `initializer_list` might work.
