### ISSUE TITLE
size and total_size of static_bounds in multi_span

### ISSUE THREAD

**Issue by bledson** [microsoft/GSL#508]
What is the rationale for `size()` and `total_size()` in multi_span (lines 645, 647), since both have the same function body (`return m_ranges.totalSize()`)?

**Comment by maikel** [comment]
This is not an answer to your question:

`multi_span` did not receive too much love here. Its development got kind of merged with another proposal (currently its called `mdspan`). I think the GSL `multi_span`-iterator suffers performance-wise from being random-accessible and should be avoided for computational purposes. Maybe it is worth to follow https://github.com/kokkos/array_ref since, I think, `mdspan` is developed there further.

**Comment by JordanMaples** [comment]
Maintainer's call: multi_span is deprecated, closing.
