### ISSUE TITLE
GCC 7.1 ambiguous extent

### ISSUE THREAD

**Issue by ladnir** [Microsoft/GSL#527]
In a cpp file, I have
```
using namespace std;
...
#include <gsl/gsl>
```
 and as a result, when compiling with g++ 7.1 I get the following:
```
 /home/dd/Documents/git/libOTe/cryptoTools/cryptoTools/../cryptoTools/gsl/multi_span:
             In member function ‘constexpr gsl::multi_span<ValueType, FirstDimension, 
             RestDimensions>::size_type gsl::multi_span<ValueType, FirstDimension, RestDimensions>
             ::extent() const’:
 /home/dd/Documents/git/libOTe/cryptoTools/cryptoTools/../cryptoTools/gsl/multi_span:1496:43: error: 
              type/value mismatch at argument 1 in template parameter list for ‘template<class, unsigned
              int <anonymous> > struct std::extent’
   return bounds_.template extent<Dim>();
                                  ^
```

It the compiler appears to be confusing static_bounds<...>::extent< Dim>() with struct std::extent<class T,...>() 

My fix was to just remove the using namespace. But I thought this might be something the gsl would want to avoid.

**Comment by galik** [comment]
Putting `using namespace std;` before *including* headers is very likely to cause odd and hard to spot bugs in your code. I don't think any library can code around all the possible things that can go wrong because of it.

Removing `using namespace std;` is the correct fix here imo.

It's considered by many to be bad practice to use `using namespace std;` pretty much anywhere but if you *must* use it, put it **after** all your *included* headers and if possible restrict it to the scope in which it will be used (say in a function body).

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#sf6-use-using-namespace-directives-for-transition-for-foundation-libraries-such-as-std-or-within-a-local-scope-only

**Comment by ladnir** [comment]
Yes, I agree with not using  "using namespace std;". Not sure how it got in there in the first place ;). Just thought I would mention it. Happy for this simply to be closed if that's how the devs feel.

**Comment by CaseyCarter** [comment]
FYI, I've filed this bug as [GCC PR 81026](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81026).
