### ISSUE TITLE
including <iostream> not always desired

### ISSUE THREAD

**Issue by menete** [Microsoft/GSL#567]
When running on an embedded Platform (like ARM Cortex-M) including `<iostream>` is not always desired – it usually increases the code size dramatically (200 … 300 kB – on targets with usually less than 1 MB of memory).
The `<iostream>` include in the ‘gsl/gsl’ file hence prevents efficient use of the not_null class.
Some options might be

- isolate the not_null into a dedicated header (not having the `ostream& operator<<` function, and keep the `operator<<` within the ‘gsl/gsl’ file.
    This would allow to do `#include <gsl/not_null>` the same way it is currently possible for `#include <gsl/span>`).

- replace `#include <iostream>` by `#include <iosfwd>`
    While this seems to work (and solves the code bloat issue) I’ mot sure whether this is the right thing to do, with respect to the `ostream operator<<` definition within this file.

I can offer to do those changes, provided some agreement on which option to choose.

**Comment by neilmacintosh** [comment]
I certainly appreciate the frustration @menete. But for my education: this can't just be a problem for `not_null`....doesn't this same problem present itself with use of `std` types such as `string` and `string_view`?

**Comment by menete** [comment]
@neilmacintosh It is - but has a different order of magnitude.
Just adding a `std::string` to a simple  "Hello World" example will have quite some impact on the code size - as a  `std::string` will bring quite some dependencies (heap functions, ...).

Starting from a simple "Hello World" example, which just toggles an I/O pin. The code size of the Debug Build (gcc 7.2, C++14, -O0, newlib default) evolves like this.

- ~ 2.5 kB exceptions/rtti disabled

- ~ 14 kB exceptions/rtti enabled

- ~ 76 kB when including a `std::string` variable

- ~ 282 kB for `#include <iostream>`

This is just to provide some examples. Whether exceptions are suited for an embedded target or not would be a non-trivial discussion.
Nevertheless embedded systems usually avoid dynamic memory management (due to reasons of heap fragmentation) - hence `std::string`, `std::vector`, ... 
However therer is no reason not to use `gsl::span`, `gsl::not_null`, `std::array` (or `boost::static_vector`)

**Comment by neilmacintosh** [comment]
@menete Thanks for the data: very interesting! I raised std::string as an example because it does include definitions (at least in our stdlib implementation) of `operator<<`, and hence should include <iostream> (or at least enough of it to hurt).

I take your point, though, about the difference in utility between `std::string` and `gsl::span` in tightly constrained environments like embedded targets.

If replacing `<iostream>` with just `<iosfwd>` would work - and all existing users would need to do would be to add an additional include of `<iostream>` if they actually invoke `operator<<`, it seems like the path of minimal disruption and the best option. But I haven't tried that...does it really work?

I'm not sure otherwise how good a user experience it would be if people included `<gsl/pointers>'  but didn't get `operator<<` unless they additionally included `<gsl/gsl>'.

**Comment by menete** [comment]
I have created a new Pull Request #586 based on the `<iosfwd>` approach.
It superseeds #576.
As remark for the tests:
As the catch framework already includes `<iostream>` no additional includes are required.

**Comment by neilmacintosh** [comment]
Thanks for taking the time to report and work through a solution for this issue @menete. #586 has been merged, so I think we can close this out.
