### ISSUE TITLE
Introduce versioned releases

### ISSUE THREAD

**Issue by AMDmi3** [Microsoft/GSL#595]
GSL seem to be relatively widely used, however it doesn't have any official versioning/release scheme, which makes packaging a mess:

https://repology.org/metapackage/ms-gsl/versions

Perhaps it's time to introduce official versions/tags/releases?

**Comment by markyin** [comment]
good suggestion

**Comment by Farwaykorse** [comment]
To state my situation.  
I'm running into the issue fixed in #587, generating errors with the update to VS15.5.
Now I'm about to create a pull request for vcpkg, but the lack of information doesn't make this any easier. I can either assume the current HEAD of master is good enough, or try to pick a better suited commit. This requires me to check the issues, CI results, and try it for myself on my limited code-base. And then, without any in-dept knowledge of the state of this project I'll push it to everyone else using vcpkg.

I might not know much about the CI implementations, but the current implementation doesn't really help.
The latest AppVeyor 'passed' with most compilations cancelled, while the previous passed test is a month old.
The last TravisCI build is failing on most builds, because of (when I check the logs) a series tests not being run.  
All this makes for a 'close your eyes and jump'-like experience.

------
Even if the head of master is always considered to be stable.
Most users and especially packaging systems, aren't going to update on every single commit.  
At the same time, without ploughing through this repository, there is no indication that the current head is any better than a random version in February.

------
Therefor I'd like to request:
- the addition of a tagged versions, considered good enough by maintainers of the gsl, while marking major additions and important fixes.
- a simple change log tracking these.

**Comment by paweldac** [comment]
@Farwaykorse 
CI for current HEAD@master: 
https://travis-ci.org/Microsoft/GSL/builds/311420274
https://ci.appveyor.com/project/neilmacintosh/gsl/build/0.1.614

single task was not executed at travis. I also agree that gsl should be versioned. During packaging I found it difficult to detect if gsl is installed in the system. Due to lack of versioning simple pkgconfig cannot be exported during library installation. I've made changes to CMake to export cmake config here: https://github.com/Microsoft/GSL/pull/574. When any versioning will be available to gsl project I'll be more than happy to update PR with pkgconfig creation during installation.

**Comment by paweldac** [comment]
similar issue was rised here: https://github.com/Microsoft/GSL/issues/537

**Comment by rsjaffe** [comment]
And #599

**Comment by ketjow4** [comment]
+1 it will be great to have some versioning and changelog

**Comment by janhenke** [comment]
I package this project for Gentoo, having tagged releases would really help. It is not easy to know right now which git revisions to pick for packaging.

**Comment by MikeGitb** [comment]
When in doubt: The newest one.

**Comment by janhenke** [comment]
The point is: It is not practical to package every new git revision, so you have to pick one. Right now there is no indication at which point certain features are more or less complete or if some important bug fixes are included. So having a tagged release once in a while would help distributions a lot. It would also make it easier to track changes.

**Comment by MikeGitb** [comment]
@janhenke: Don't get me wrong: I asked about versioned releases long ago and would be glad to see them (similar topic with the coreguidelines). The thing of the matter is that development of the library doesn't follow any release cycle anyway. API breaking changes are introduced at any point in time, but at the same time, the featureset has pretty much stabilized, so I'm not sure any versioning tags by Neil would be less arbitrary than you just picking the latest version every couple.

**Comment by neilmacintosh** [comment]
I'll admit I failed to make any progress in this regard. I'll hand this issue over to @annagrin, who might have more success.

**Comment by annagrin** [comment]
@MikeGitb  has a point. Every PR merge is validated, so most tags will be pretty much arbitrary.

The only time GSL receives extra testing from our side is when the change is significant or API-breaking, so I test it by compiling our own code relying on GSL. I could mark those points with some versioning scheme if that solves the issue. Any thoughts?

**Comment by janhenke** [comment]
@annagrin Sounds good to me. That would definitely help in choosing which revision to package for distributions.

**Comment by AMDmi3** [comment]
@annagrin Yes, that makes sense.

**Comment by annagrin** [comment]
Thanks everyone, I've introduced version v1.0.0, marking the last commit that we verified by compiling and testing our own code that uses GSL.
