### ISSUE TITLE
span constructor for const pointer plus length

### ISSUE THREAD

**Issue by fesun** [Microsoft/GSL#634]
Span doesn't accept const pointer plus length for construction, what's the reason for this? It should be common to use span as const view.

**Comment by neilmacintosh** [comment]
Hi @fesun. I'm pretty sure that `span` does work with a `const` pointer. Are you sure you are using the `const T*` and length to initialize a `span<const T>` and not a `span<T>`?

**Comment by neilmacintosh** [comment]
Ok. I'm going to close out this issue for now. @fesun if you still think there's a problem, feel free to reopen it!

**Comment by fesun** [comment]
@neilmacintosh thanks, span<const T> works. Usually use const vector<T> to indicate this vector is not mutable, I am not sure why gsl chooses span<const T> instead of const span<T>?

**Comment by neilmacintosh** [comment]
@fesun it's an understandable confusion.`span` follows the pattern of: use `const T` if you want read-only elements, use `const span` if you want a read-only span (i.e. it can't be reassigned to have a different length/sequence). `vector` follows a different pattern, partially because it was designed at a different time, but it is also a container.
