### ISSUE TITLE
span_iterator& operator+= might rely on undefined behaviour

### ISSUE THREAD

**Issue by snf** [microsoft/GSL#638]
In https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L198:
```
        constexpr span_iterator& operator+=(difference_type n)
        {
            Expects((index_ + n) >= 0 && (index_ + n) <= span_->size());
            index_ += n;
            return *this;
}
```
`(index_ + n) >= 0` checks the resulting addition of two signed integer types. If the check happens to overflow, then the comparison is relying on C++ unspecified behaviour.
Please correct me if I'm wrong.

**Comment by MikeGitb** [comment]
What do you mean by rely on? If an overflow happens it is UB and th span_iterator gives no guarantees on what happens. Or are you suggestin the operator should check for overflow before doing the addition?

**Comment by snf** [comment]
Hi Mike, the former. My question is regarding code like this (I hope no-one uses iterators like this though):
```
    std::vector<int> v = { 1, 2, 3 };
    span<int> s{ v };
    auto it = s.end();
    auto might_underflow = it[PTRDIFF_MAX];
```
This will UB in `(index_ + n)`. So my question is if span_iterator should check the addition doesn't overflow?

**Comment by galik** [comment]
This is a really interesting point because if the `Ensures` sanity checks invoke UB, we're doomed. I always assumed that UB due to integer overflow would be fairly predictable and probably only a problem on some weird theoretical CPU architecture that only about 5 people use. Then I saw this post on Stack Overflow https://stackoverflow.com/questions/48731306/program-behaving-strangely-on-online-ides#comment84461782_48731306 . Terrifying.

**Comment by MikeGitb** [comment]
Ensures only invokes UB, if the according operation would do so anyway, so using it is certainly not worse than without the check. Of course, one could check for overflow in addition - e.g. something like

     Expects( PTRDIFF_MAX - index_ > n);

or maybe one could probably just rely on UBSAN.

@galik: It almost doesn't matter what kind of UB we are talking about: The reason is UB is scary is almost never related to the hardware, but always due to compiler optimizations.

**Comment by beinhaerter** [comment]
@snf I appreciate that you are looking at UB cases and that you want to fix the expression in Expects. I think it's a good idea to change the Expression, but I fear that it will only (but at least) work for debug mode without optimization. An optimizing compiler might optimize away some checks because the function body has UB. But that can only be fixed in the function body (which shouldn't be changed) and not in the Expects.

**Comment by snf** [comment]
Thanks @MikeGitb  and @beinhaerter. Both points make sense and I'm not aware of any optimization affecting that specific expression. I will think more about it later.

**Comment by JordanMaples** [comment]
Closing this as the span_iterator class has been completely rewritten. Please reactivate this issue if you spot any issues with the new implementation. Thanks.
