### ISSUE TITLE
gsl::make_span from std::wstring doesn't compile in VS2015

### ISSUE THREAD

**Issue by gicutza** [microsoft/GSL#656]
VS 2017 15.6.6 (toolset v140)
```c++
#include "stdafx.h"
#include <string>
#include "gsl\gsl"

int main()
{
	std::wstring s;
	auto r = gsl::make_span(s);

    return 0;
}
```
**Build output:**
```c++
1>xxx\3rdparty\include\gsl\span(394): error C2664: 'gsl::span<wchar_t,-1>::span(gsl::span<wchar_t,-1>::KnownNotNull,gsl::span<wchar_t,-1>::index_type)': cannot convert argument 1 from 'const wchar_t *' to 'wchar_t *'
1>xxx\3rdparty\include\gsl\span(394): note: Conversion loses qualifiers
1>xxx\3rdparty\include\gsl\span(678): note: see reference to function template instantiation 'gsl::span<wchar_t,-1>::span<Container,void>(Container &)' being compiled
1>        with
1>        [
1>            Container=std::wstring
1>        ]
1>xxx\3rdparty\include\gsl\span(678): note: see reference to function template instantiation 'gsl::span<wchar_t,-1>::span<Container,void>(Container &)' being compiled
1>        with
1>        [
1>            Container=std::wstring
1>        ]
1>xxx\src\ttt\ttt.cpp(8): note: see reference to function template instantiation 'gsl::span<wchar_t,-1> gsl::make_span<std::wstring>(Container &)' being compiled
1>        with
1>        [
1>            Container=std::wstring
1>        ]
```

**Comment by beinhaerter** [comment]
I don't want to argue if GSL is doing it right or not, so this post is just to help you getting it compiled.

If you are passing a non-const container to `make_span`, then you get a `span` of non-const values. `span` is using `container.data()` to get access to the data. A `std::wstring` has these member functions:
- `const wchar_t* data() const;`
- `wchar_t* data();`   // since C++17

So the mismatch here is that `make_span` generates a `span<wchar_t>` but the `span` constructor can only retrieve a read-only `wchar_t*` before C++17 where it really would need a non-const `wchar_t*`.

If you are using a compiler before C++17 and if a read-only `span` is sufficient for you, then you can write

    auto r = gsl::make_span(const_cast<const std::wstring&>(s));

If you need the non-const `span` then as of today you'll need to use C++17.

**Comment by galik** [comment]
I guess this is what `<gsl/string_span>` is for. For some reason there are not `gsl::make...` functions for the *string* versions but you can create one directly like this:

	std::wstring s;
	auto r = gsl::wstring_span<>(s);

The constructor uses `&s[0]` rather than `s.data()` to produce a writable span.

**Comment by gicutza** [comment]
gsl::basic_string_span isn't a gsl::span and I don't think I understand why isn't

The code from the first post is a very simple sample, but if I want something like:
```c++
void f(gsl::span<wchar_t> s)
{
...
}

std::vector<wchar_t> v = {...};
f(v);
std::wstring s = L"...";
f(s);
```
then I must implement 
void f(gsl::wstring_span s)

**Comment by neilmacintosh** [comment]
A few comments here:

1. `gsl::basic_string_span` is not a `gsl::span` because it had to offer at least one different constructor (working from memory), and we wanted to be able to evolve `span` separately as part of standardization. Also, you wouldn't want users assuming the two are the same type when they are not necessarily so.

2. The existing `make_span` functions are not part of the `std::span` specification. I would not rely on them too heavily at this point, as they may end up deprecated. The feeling in discussions at committee meetings was that if the constructors are correctly specified, the `make_span` functions should not be necessary. (Of course, if people have contrary evidence, this is as good a place as any to provide it).

**Comment by JordanMaples** [comment]
Maintainers' call: VS2015 is no longer supported. Please reactivate if you see this issue on a newer compiler.
