### ISSUE TITLE
gsl::at logs a signed/unsigned mismatch when used with span

### ISSUE THREAD

**Issue by rexjolliff** [microsoft/GSL#706]
something like the following code generates a signed/unsigned mismatch for less than (<).

gsl::span<char>  aSpan;

char x = gsl::at (aSpan, 2);

Probably due to the bounds check, the gsl::span uses ptrdiff_t (signed) as the size type, and gsl::at takes a size_t (unsigned) as the second parameter.

**Comment by annagrin** [comment]
The purpose of `gsl::at` is to safely access standard containers, which have unsigned indices. `span` does not need it since it have a range check built-in.

**Comment by beinhaerter** [comment]
@annagrin
The samples in ES.42 and SL.con.3 use `int` as index type, not `size_t`.
Searching the CppCoreGuidelines I do not see any comment that `gsl::at` is only for STL containters.
I think that having a free function `gsl::at` for unified Syntax and allowing also `gsl::at` for `gsl::span` without warnings looks like a good idea to me.
And last but not least there have been long discussions that indexes shall be `ptrdiff_t` and not `size_t`.
To make it short I agree with rexjolliff and think that it would be nice to have a fix for this.

**Comment by annagrin** [comment]
@beinhaerter @rexjolliff are you interested in submitting a PR?

**Comment by rexjolliff** [comment]
Really, that was the intent of my post here. Is there a more formal way of submitting a problem for GSL?

**Comment by neilmacintosh** [comment]
@rexjolliff in this context, "PR" stands for "pull request" rather than "problem report". Consider this issue a formal problem report. @annagrin is asking if anyone would like to offer a diff with a fix ;-)

**Comment by rexjolliff** [comment]
Unfortunately, I dont have time to fix it right now.  And, even if I did, it seems like there is perhaps some varying opinion on what should change...

**Comment by beinhaerter** [comment]
@rexjolliff Can you please show the exact code that you tested? Take caution to mark it as code so that template parameters like in `gsl::span<char>` are not interpreted as HTML tags.
What exact warning do you get? Which GSL version/commit did you use? Can you test with the latest version 2.0? Which compiler do you use? MSVC or somethings else?

@annagrin My test code below compiles without warnings with GSL 2.0 and VS 15.8.1 with warning level 4. I assume there has been a change in the compiler (see my comparison `str.length() < len`)!? Something like the CppCoreGuidelines suggest in the Enforcement of [ES.100/Res-mix](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-mix) or [ES.107/Res-subscripts](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-subscripts)? Regarding warnings inside GSL maybe for MSVC you already fixed them with one of your latest commits?

```
#include <iostream>
#include <string>

#include <gsl/gsl>

void f()
{
	std::string str;
	std::cin >> str;
	const int len{ 5 };
	if (str.length() < len) {
		return;
	}

	const gsl::span<const char> aSpan(str.c_str(), 5);
	const char x = gsl::at(aSpan, 2);
	std::cout << x;
}
```

**Comment by rexjolliff** [comment]
@beinhaerter I took your code and compiled it with /W4 and I get a signed/unsigned mismatch in gsl_util.h line 129. I changed the include to gsl.h, apparently I am installing GSL differently (from a NuGet). I am using MSVC v15.8.1.

**Comment by pgroke-dt** [comment]
I guess this can be closed now that `span` has been changed to using an unsigned `size_type`. BTW: We'd like to use a new version with the unsigned `size_type` - when is the next release planned?

**Comment by JordanMaples** [comment]
I'm planning a release for mid to late April. There are a couple changes in span that I would like to merge before I push the new release.

**Comment by pgroke-dt** [comment]
Sounds great, thank you :)

BTW: Sorry for mis-using this issue by asking about the next release - I just didn't find any other place to ask questions.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
