### ISSUE TITLE
Why `czstring_span` has member functions of the form `::ensure_z()`, `::assume_z()` rather than `.data()`

### ISSUE THREAD

**Issue by garbageslam** [microsoft/GSL#726]
To my understanding, `czstring_span` represents a (const) range of characters known to have a null terminator. The constructor enforces that there is a null terminator, the length is stored so that no one in the future needs to call `::strlen` (which is a security risk).

Why does `czstring_span` have methods of the form `ensure_z`, `assume_z` rather than `.data()` and `.size()`? The ensuring / assuming is already done in the constructor, right? It makes the code more difficult to read and understand if the API forces unnecessary checks to be made and forces people to use an odd syntax.

**Comment by cbeck88** [comment]
Thanks for your comments.

I was hoping that `czstring_span` was supposed to fill a niche like described by Nicol Bolas on stackoverflow here: https://stackoverflow.com/a/41288372/3598119

I didn't realize that wasn't what this is for.

I guess it is also true that just because I have a pointer (e.g. `const char *`) to a string that I myself am not allowed to change, doesn't mean that someone else isn't allowed to change it. However it's hard for `zstring_span` ever to be correct if it is abused in this way -- why give out a `zstring_span` to a string, promising null terminator is there, if you or someone else may later remove the null terminator? Why not just use span in that case?

Thanks a lot for your feedback, I will look elsewhere for a `zstring_view` or some such that fits my usecase. I'm mainly interested in a safer type than `char *` for use in C++ code that can wrap string literals / strings that have been printf'd so that they can later be passed to linux / C library APIs.

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. This is issue is now out of date because the Guidelines have removed all `*string_span` types, and it still has `zstring` and `czstring` as aliases for `char*` and `const char*` which don't have member functions.
