### ISSUE TITLE
single argument constructors should be explicit

### ISSUE THREAD

**Issue by beinhaerter** [Microsoft/GSL#730]
I have at least seen some single argument constructors for `span` and `multi_span` that are not marked `explicit`. Wouldn't it be better to mark them `explicit`?

This issue is related to issue #120 which requested to _define this [macro implicit], and use it in the gsl classes_. That issue was closed after the macro part was clarified at the CppCoreGuidelines (no macro, prefer the attribute `[[implicit]]`) but then the second part _and use it in the gsl classes_ was not done.  So if `[[implicit]]` is preferred, maybe we could use that? But I am not sure how that should work as I can't find any information that `[[implicit]]` has made it into the C++ standard or that `[[gsl::implicit]]` exists.

**Comment by jack17529** [comment]
So Neil has to say something here?

**Comment by neilmacintosh** [comment]
@jack17529 thanks for the ping here.

The constructors of `span` are not `explicit` by design. Given that `span` is a general-purpose view type, the implicit constructors exist to allow for simple argument passing. Especially at legacy callsites where a function might have previously taken (ptr, len) and now add an overload that takes (span). So this issue should be closed now (which I'll do).

@beinhaerter: feel free to reopen or open a new issue if you think some of the `multi_span` constructors might not fit in the same category.
