### ISSUE TITLE
Request: Conda package

### ISSUE THREAD

**Issue by sdrobert** [microsoft/GSL#768]
Hi,

[Conda](https://conda.io/en/latest/) is a centralized repository for many libraries, open source or otherwise. I would like to request a conda package for the guidelines support library, which would help centralize the distribution of the library for those who work in the ecosystem.

Thank you for your time,
Sean

**Comment by WSLUser** [comment]
conda is for python, not for  C or C ++. PythonC uses a C compiler but still isn't the same and highly doubtful this will ever work with python without some magic in which python reads some C/C++ files using PythonC (or something similar). But that would mostly defeat the purpose of python. It's one thing to use a C compiler to improve performance, quite another to use it to read a bunch of files that do all the heavy lifting.

**Comment by sdrobert** [comment]
@WSLUser Thank you for your reply. While I disagree that "conda is for python," as it does a very good job handling the distribution of C/C++ libraries without the need for python (I personally use it in our school's server clusters to ensure consistent libraries at runtime), I grant that the primary audience is python developers.

As for the rest of the message, I think you're saying that python would not be able to directly benefit from the GSL, since the syntax python extensions can handle is only up to C++11? If so, it's worth mentioning that only the code used to interface with the C++ libraries needs to be C++11. Extensions are usually compiled with GCC, clang, or vs compiler (IIRC python 2.7 needed a special compiler for Windows, but the rest are just VS).

In any event, I understand this being low on the list of priorities. Thank you for your time.

**Comment by OvermindDL1** [comment]
> without the need for python

So it doesn't require python to be installed to use it as a packaging system, does it have a full local cmake module for full cmake integration without python?

**Comment by sdrobert** [comment]
@OvermindDL1 that's correct.

To illustrate, here I've asked for a conda environment to be created with the only requirement being CMake on linux. Note the lack of Python anywhere.
```
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.5
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /xxx/miniconda3-latest/envs/dummy

  added / updated specs:
    - cmake


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h7b6447c_0         105 KB
    cmake-3.14.0               |       h52cb24c_0         5.5 MB
    expat-2.2.6                |       he6710b0_0         146 KB
    krb5-1.16.1                |       h173b8e3_7         1.2 MB
    libcurl-7.65.2             |       h20c2e04_0         588 KB
    libssh2-1.8.2              |       h1ba5d50_0         226 KB
    rhash-1.3.8                |       h1ba5d50_0         188 KB
    ------------------------------------------------------------
                                           Total:         7.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.5.15-1
  cmake              pkgs/main/linux-64::cmake-3.14.0-h52cb24c_0
  expat              pkgs/main/linux-64::expat-2.2.6-he6710b0_0
  krb5               pkgs/main/linux-64::krb5-1.16.1-h173b8e3_7
  libcurl            pkgs/main/linux-64::libcurl-7.65.2-h20c2e04_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libssh2            pkgs/main/linux-64::libssh2-1.8.2-h1ba5d50_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1c-h7b6447c_1
  rhash              pkgs/main/linux-64::rhash-1.3.8-h1ba5d50_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
```

Here's the same for Windows:
```
λ conda create -n dummy cmake
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\conda-envs\dummy

  added / updated specs:
    - cmake


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cmake-3.14.0               |       h33f27b4_0         6.0 MB
    ------------------------------------------------------------
                                           Total:         6.0 MB

The following NEW packages will be INSTALLED:

  cmake              pkgs/main/win-64::cmake-3.14.0-h33f27b4_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.15.26706-h3a45250_4
```

The only issue I've found with conda and CMake is described [here](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots). Otherwise, it's really convenient.

**Comment by WSLUser** [comment]
In order to use the conda package manager, I don't see how you would get it without installing python as you would at the very least need to install Miniconda, which includes python You would have to build the source yourself.  

As far as the rest of what I said goes, perhaps I'm not quite as informed on the relationships between python and C but what I do understand is pure python uses completely different syntax and writing python is so much simpler and easier than C++, C, or even C#. That said,  there are times when it's best to use C++ or C# instead of python.

**Comment by WSLUser** [comment]
I think you would be better served having GSL managed through snapcraft and flatpak (and offered up on the individual distro repos for special distros). Everything you show getting installed already exists on your Linux system.

**Comment by OvermindDL1** [comment]
Yeah I'm not seeing how it would work without python either, you seem to be using some kind of `conda` command, which involves installing 'something' that is not cmake or the base essentials build system.  Take hunter.sh (sadly dying due to lack of people helper), you add a cmake modules to your project, then you can just `hunter_add` in things into your project, it will auto-acquire the requested specific version, compile it to a cache (all of this configurable or even disableable to use system instead) and all behind the scenes, all in pure cmake, then using normal cmake `find_package` and all to grab the depended on versions of the dependencies.  It requires installing nothing to build, requires no runtimes to install, it's literally just `git clone`, `cmake -H. ... build ...` and it it all automatic, nothing but cmake and `build-essentials` needed for example.  Any dependency system that requires more work than that (like vcpkg and others are so inherently broken in this way) will be annoying to use and thus will not become highly used.  C++ needs to become more like rust (and most modern languages) in this way, where the dependency management is in the build system, not some weird 'other' thing you have to install and run 'special' commands to use.

**Comment by WSLUser** [comment]
For a Windows user like me, I'd say if you wanted to distribute for other than Linux, then a Chocolatey package should be created, which would be far more appropriate and much easier to establish.

**Comment by sdrobert** [comment]
You're both right: Miniconda itself is built off Python, and certainly not CMake, even if the environments themselves don't require Python. From a purity perspective, it's not a hunter.sh. However, one thing it does offer that AFAICT isn't offered by the alternatives proposed is self-contained environments that do not require super user or admin. It also has an established user base in the machine learning ecosystem (admittedly, the C++ is largely transparent to the end user), and is actively maintained by the folks at Anaconda.

My personal take is that package managers are made popular by a combination of convenience, availability, and marketing -- less so purity. However, I am only a graduate student in a field that doesn't prize good programming practice, so I'll defer to the experts here.

**Comment by OvermindDL1** [comment]
> However, one thing it does offer that AFAICT isn't offered by the alternatives proposed is self-contained environments that do not require super user or admin

Hunter.sh does not require any special super user or admin (and honestly I'd **highly** question any dependency management system that does!), it's cache directory is the only thing it touches outside of the project directory and that's in `$HOME`, and even that is configurable.

> convenience, availability

These two are significant barriers to third-party installed packages on systems where it needs to be built on, such as conda and vcpkg.

> marketing

And this I have 30+ year personal biases about relating to marketed products often (though not always) being among the worst and/or locked-in products in the category...  ^.^;

**Comment by WSLUser** [comment]
I use conda on Windows for my python projects. Venv for linux. Pip works well enough for me in most cases. I think what you're wanting is a containerized environment. What you really want is a `venv `  equivalent but the closest you'll get is a chroot. Well if you want to work in a container, then live in a container, that's why we have Docker.

**Comment by sdrobert** [comment]
@OvermindDL1 @WSLUser thank you for your time.
