### ISSUE TITLE
byte operator |= (and &= and ^=) cause possibly spurious lifetime.4 warnings

### ISSUE THREAD

**Issue by dorssel** [microsoft/GSL#776]
Latest VS2019 with "All Rules" analysis produce C26487 warnings in gsl_byte. I think the warning is spurious and I have already reported it:
https://developercommunity.visualstudio.com/content/problem/522681/vs2019-c-spurious-warning-c26487-on-returning-a-va.html

But in the mean time maybe GSL could suppress the warning, considering the whole purpose of GSL is to get nice and warning free code...

**Comment by hsutter** [comment]
Maintainers' call: Thanks, closing this specific issue as the DevCommunity bug is now closed as no longer repro. We have moved Lifetime checks to Experimental Rules and the GSL should build cleanly without that. We'll work on further improving this so that Lifetime checks are non-experimental in the future and GSL compiles clean.
