### ISSUE TITLE
un-caught GSL error using span<T> argument

### ISSUE THREAD

**Issue by BullRancor** [microsoft/GSL#783]
I have the following code:

```
#include <iostream>
#include <gsl/gsl>

typedef struct Thing
{
    int x;
    int y;
    unsigned   GetSize() const noexcept
    {
        return sizeof(Thing);
    }
}Thing;

void f(gsl::span<const Thing> things) {
    unsigned totalSize = 0;
    for (auto& aThing : things)
    {
        totalSize += aThing.GetSize();
    }

    std::cout << "Total size of array of things: " << totalSize << std::endl;

}

int main(int argc, char** argv)
{
    Thing things[10];
    f(things);
    f({ things,5 });
    f({ things,30 });  //i think this should be a caught by the compiler, but it's not
    
    return 0;
}
```
(note that this code comes from "CppCon 2015: Neil MacIntosh “Evolving array_view and string_view for safe C++ code", at 1:47 into the video)

I think the reason to use span<T> was so that the compiler could catch array bound errors, 
like in the third call to f().

In his video, Neil MacIntosh says this should cause a compiler error/warning.

I compiled with VS2017 and g++ and neither gave the error that I expect.  Do I need to tell the compiler to do the array bounds check?

Also, both executables ran without error and produced the following output:

```
Total size of array of things: 80
Total size of array of things: 40
Total size of array of things: 240
```

**Comment by beinhaerter** [comment]
I just watched the relevant part in the video and now understand where you are coming from. I don't have an idea what Neil means. Even when going back to commit 54f832115bb50b42163511e659763d1f4f0b5129 from 4. November 2015 I don't see a compiler error for `f({ things, 30 });`. Even back further with f1be21aa36c67f7535d57f9d942235a9ba1096c1 where the namespace was still `Guide` and not `gsl` there is no compiler error.

As @neilmacintosh is the speaker and also a contributor here, I suggest we just ask him so that he can explain it himself :).

**Comment by neilmacintosh** [comment]
Thanks for paging me @beinhaerter ;-)

This is not very tricky or deep. There are lots of things that the compiler can simply prevent from compiling if you use `span` that would be incorrect. Today's `span` offers a lot of those safeties, as well as the additional safety of runtime checks where compilation errors can't be guaranteed. So...yes, @BullRancor, runtime safety is better than no safety is the principle in use there.

Regarding the "pointer, length" constructor: there is currently no reliable way in C++ to make that constructor always be safe at compile time. So it is - to a large extent - a "trust me, this is safe" operation sadly. In my talk, I was referring to the idea that you *could* build an analysis that determined whether or not calls to that constructor were actually safe. Such an analysis could exist in separate tooling or it could be implemented within a compiler. Such an analysis could not guarantee all uses of the constructor were safe (because C++ has lots of tricky corners and sometimes pointers come from places the compiler can't see), but it could certainly verify a subset. 

So as a sketch of an example implementation: some calls to that constructor could be checked at compile time, the ones that could not could be flagged with a warning in case you wanted to do additional manual checking. 

The talk was presenting `span` and friends in terms of where we hoped it could get to with support from a compiler toolchain. Maybe we'll eventually see a toolchain offer something like these additional safety checks.

Hopefully that answers the questions!
