### ISSUE TITLE
GSL violates CppCoreGuidelines both ES.32 and ES.33:

### ISSUE THREAD

**Issue by jmatzen** [microsoft/GSL#801]
https://github.com/microsoft/GSL/blob/1212beae777dba02c230ece8c0c0ec12790047ea/include/gsl/gsl_assert#L170

Naming violates both ES.32 and ES.33:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-interfaces

"Scream when you see a lower case macro." While it's not entirely lower case, obvious violation is obvious.

**Comment by B1Z0N** [comment]
It is necessary, because it is another feature of GSL(see [I.6 Expects](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i8-prefer-ensures-for-expressing-postconditions) and [I.8 Ensures](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i8-prefer-ensures-for-expressing-postconditions). 

So it should stay named this way. We can change it to constexpr function, but two obstacles in our way:
1. Not all compilers supporting gsl also support constexpr(not sure about this, i am new to this library, likely it is true, is it?).
2. Why do we need to bother the compiler if we could just use  bare macro and bother preprocessor? which seems to be a lot faster(not sure about this too, but i know that C++ compiler is slow, so preprocessor is likely to be faster, because it is more mindless, in a good way).

Yeah, i bet core guidelines have self-violations. It is a complex system, and self-violations are a property of complex systems.
