### ISSUE TITLE
Improper use `std::forward`

### ISSUE THREAD

**Issue by tomilov** [microsoft/GSL#846]
[Here](https://github.com/microsoft/GSL/blob/master/include/gsl/gsl_util#L79-L89) `F` in second overloading has always value (non-reference) type if just deduced. Therefore using of `std::forward` is improper (though works).

**Comment by ArtemSarmini** [comment]
Should be
```c++
template <class F>
final_action<std::decay<F>::type> finally(F&& f) noexcept
{
    return final_action<std::decay<F>::type>(std::forward<F>(f));
}
```
or more specific `remove_reference<remove_const<F>::type>::type` instead of `decay`

**Comment by johelegp** [comment]
You got the reference and const backwards.

**Comment by ArtemSarmini** [comment]
Edited

**Comment by CaseyCarter** [comment]
I came here to make an argument for why the decay is unneeded, but looking at the implementation of `final_action` I'm confused. The use of `std::move` in the member initializers suggests that `final_action::f_` is intended to be a function object. (The unconditional `noexcept` on both constructors is unfortunate, since it will cause the program terminate if the initialization of `f_` throws an exception - perhaps the intent is that `f_` is always a function pointer?) The fact that `final_action` is move constructible seems to contradict the intent of the Core Guidelines that it only be usable in a local scope.

In any case, I agree with statement in the original edition of the first post which suggested that the `finally(const F&)` overload is redundant given existence of the perfect-forwarding `finally(F&&)` overload. Whether that overload should return `final_action<F>` or `final_action<std::decay_t<F>>` is then a consequence of the design intent for `final_action` itself. Is it intended that:

* `final_action` internally stores a function object, which can be moved (along with the responsibility for invocation) into another `final_action` object (always `decay` argument types), or

* `final_action` is usable only within a local scope under the assumption that lvalue arguments passed to `finally` must be valid at the resulting `final_action`'s point of destruction (don't decay so lvalues are captured by reference and rvalues by value)?

Either design can be implemented, but it's not clear to me which design is intended.

**Comment by johelegp** [comment]
The influence on the existence of the move constructor must have some from a discussion I remember in some issue/PR here or at CppCoreGuidelines. It was about being able to return a `final_action` or invalidate it so as to not invoke the final action anymore.

**Comment by Odept** [comment]
Also, is there a reason why the `final_action` ctor doesn't take an rvalue-ref: it's `final_action(F f)` instead of `final_action(F&& f)`? Dosn't it always result in a copy as a result?

**Comment by jwakely** [comment]
@tomilov 
> Here F in second overloading has always value (non-reference) type if just deduced.

If you call `finally(non_const_lvalue)` it will use that second overload and deduce `F` as an lvalue-reference type.

btw you can use "copy permalink" to get a link that won't be invalidated if/when the content of that file changes, e.g. https://github.com/microsoft/GSL/blob/0c80f51f7c5ae947411906ae5600d46d56e491bf/include/gsl/gsl_util#L79-L89

**Comment by hsutter** [comment]
I think I finally (NPI) understand why `finally()` was written as a `const&`/`&&` overload... to eliminate a copy when you invoke it with a temporary such as a lambda. If so, the `&&` was probably never intended to be a forwarder, but was simply tripping over the horrid C++ choice to have a `&&` parameter mean "rvalue reference" when the type doesn't happen to be a template parameter but a "forwarding reference" when the type happens to be a template parameter type. And this is a template, so it started looking like a forwarder, but I'll bet it was never intended to be a forwarder at all.

I'll create a PR to re-simplify this back to what [C++ Core Guidelines C.30](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction) said which is simple and clear, and then we can discuss whether we like that PR.
