### ISSUE TITLE
GSL.owner: Ownership pointers : "dyn_array"

### ISSUE THREAD

**Issue by amdDriverGuy** [microsoft/GSL#890]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gslowner-ownership-pointers

In the CppCoreGuidelines posted on github there is mention of a dynamic array.

```
dyn_array<T> // ??? needed ??? A heap-allocated array. The number of elements are determined at construction and fixed thereafter. The elements are mutable unless T is a const type. Basically a span that allocates and owns its elements.
```

I suggest adding this feature to GSL. It's a pretty trivial class. But covers most use cases of dynamic memory. Most people don't need standard vector. Since a vector is resizable. The need a one time dynamic allocation.

**Comment by JordanMaples** [comment]
Thanks for filing this @YMba9g8j9CJp0wLoQf5y. 

I'll start writing a specification for gsl::dyn_array and get it off to the CppCoreGuidelines editors.

**Comment by hdf89shfdfs** [comment]
Any update on this?

**Comment by JordanMaples** [comment]
No update yet. I got pulled away from this for other work and haven't gotten a chance to pick it back up. There is light at the end of the tunnel though, so I will hopefully be able to pick it up soon.

**Comment by hsutter** [comment]
Maintainers' call: Thanks for the feature suggestion. Because the GSL design and feature set is owned by the C++ Core Guidelines, this is just an implementation and we follow what the Guidelines specify. So we defer all feature suggestions by opening the issue in the Guidelines repo, and in the meantime we'll close the one here which can then be reopened later when there is guidance to follow from the Guidelines' making a design/feature change. Please reactivate this one when there's a conclusion.
