### ISSUE TITLE
feat: narrow for non totally ordered types

### ISSUE THREAD

**Issue by johelegp** [microsoft/GSL#900]
The C++ Core Guidelines simply [specify `gsl::narrow`](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslutil-utilities) as `narrow // narrow<T>(x) is static_cast<T>(x) if static_cast<T>(x) == x or it throws narrowing_error`. The implementation uses relational operators, so I can't do `gsl::narrow<point<unsigned>>(point<int>{})` for my `point` type.

**Comment by hsutter** [comment]
Maintainers' call: Thanks for the feature suggestion. Because the GSL design and feature set is owned by the C++ Core Guidelines, this is just an implementation and we follow what the Guidelines specify. So we defer all feature suggestions by opening the issue in the Guidelines repo, and in the meantime we'll close the one here which can then be reopened later when there is guidance to follow from the Guidelines' making a design/feature change. Please reactivate this one when there's a conclusion.
