### ISSUE TITLE
not_null in 

### ISSUE THREAD

**Issue by PatrickMGrace** [microsoft/GSL#904]
The following code only compiles with clang using compiler explorer.  Also tried gcc and msvc, but they seem to have a problem trying to convert the null_ptr on line 6 to gsl::not_null, which is unnecessary.  I wonder if there is a fix from not_null end.
```
    #include <iostream>
    #include <vector>
    #include <gsl/gsl>
    int main(){
        std::vector<gsl::not_null<int*>> v;
        int* p_int = v.empty() ? nullptr : v[0];
        std::cout << (p_int ? 1 : 2);
    }
```

**Comment by beinhaerter** [comment]
Your code does not compile on godbolt with x86-64 gcc 10.2 (https://godbolt.org/z/5n5cWb). It emits the same warnings as MSVC.

What do you expect your conditional expression to do? What shall be the result type? `nullptr` is of type `std::nullptr_t`. Do you want to convert `v[0]` to `nullptr_t`? Sounds strange. Or do you want `v[0]`'s type `gsl::not_null<int*>`? Then why would you want to create one from `nullptr`? Or do you want an `int*` as is the type of `p_int`? The problem is that the compiler only looks at the second and third expressions of the conditional operator (`nullptr` and `v[0]`), not at how the result would be used. For details you can look into the standard (https://github.com/cplusplus/draft/tree/master/papers, 7.6.16 Conditional operator [expr.cond]).

You probably want to write

    int* const p_int = v.empty() ? static_cast<int*>(nullptr) : v[0].get();

or

    int* const p_int = [&]() -> int*{ if (v.empty()) return nullptr; else return v[0]; }();

or if you don't need `p_int` to be const

    int* p_int{};
    if (!v.empty()) {
        p_int = v[0];
    }

**Comment by PatrickMGrace** [comment]
Of course there are ways to rewrite this code to do what I want.  The code that I presented is the minimum required to produce the error that I was getting.  The original code is much more complicated and consequently took me more time than I would like to tract the problem down.  If the GSL is to be useful it should be easy to use without adding extra complexity related to strange and unexpected error messages.
