### ISSUE TITLE
Final_act should require that the object it is given is noexcept invokeable

### ISSUE THREAD

**Issue by jbcoe** [Microsoft/GSL#96]
Final_act invokes the function object it is given using a destructor. 

If the function object throws an exception then this will escape the destructor of Final_act and lead to program termination. 

If Final_act required that the function object it is given is noexcept invokable then the above will not happen.

This is not perfect though, the user can lie and mark a function object as noexcept when it is not. To me this is more tolerable as the user has made the decision to mark the function noexcept rather than Final_act deciding to invoke an exception-throwing function at destruction.

Sadly

`auto f = finally([] noexcept { close_db(); });`

is not as nice as

`auto f = finally([] { close_db(); });`

**Comment by neilmacintosh** [comment]
Given that even a noexcept function can throw (even if it should not), I'm not sure this actually gains anything. The important thing is that Final_act provides a noexcept guarantee on execution of its destructor.

**Comment by jbcoe** [comment]
I think that requiring the user to specify that the function is noexcept (and possibly be wrong) gains a little. The cost in verbosity is unattractive though.

**Comment by travnick** [comment]
In my opinion, it's very useful to explicitly say "it has to be noexcept".

We had in a project similar class, and after few unexpected program terminations, we decided to force user to mark the finalizer functions as `noexcept`, so there is an explicit warning that he has to ensure the code is well written.

It also helps on code reviews, since everyone is aware, that this function is required to be noexcept.

In result of this change, we fixed additional few potential program terminations in our software.
