### ISSUE TITLE
Using this library

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#996]
Hi

Am I right in saying that you use this library with Visual Studio 2019 / 2022 all we need to do is copy the GSL folder to our project?

Thanks for confirming.

Andrew

**Comment by dmitrykobets-msft** [comment]
Hi Andrew,

Instead of copying `GSL`, you would most likely want to copy over the `gsl` folder (lowercase, not uppercase), located within this repo as `GSL/include/gsl`.

Alternatively, in Visual Studio 2019/2022, you can configure your project's include directories to point to the `gsl` folder
on your computer. See https://docs.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-160 for instructions on how to do so.

See https://github.com/microsoft/GSL#using-the-libraries for more info on including GSL in your project.

In addition, note that you can manage your GSL installation using `vcpkg`: https://github.com/microsoft/GSL#building-gsl---using-vcpkg

Thanks,
Dmitry
